export const PRODUCTS = [
  // ── Perishable · local delivery only ─────────────────────────────────────
  {
    id: 1,
    name: 'ورق عنب بالزيت والليمون',
    nameEn: 'Stuffed Grape Leaves with Olive Oil & Lemon',
    family: 'أسرة الزهراني',
    familyEn: 'Al-Zahrani Family',
    sellerCity: 'الرياض',
    sellerCityEn: 'Riyadh',
    price: 45,
    originalPrice: null,
    rating: 4.8,
    reviews: 127,
    badge: 'الأكثر مبيعاً',
    badgeEn: 'Best Seller',
    badgeColor: 'bg-amber-500',
    emoji: '🍇',
    images: ['🍇', '🫙', '🌿', '🫚', '🍋'],
    gradient: 'from-green-200 to-emerald-100',
    isPerishable: true,
    deliveryType: 'local',
    description: 'ورق عنب طازج محشو بالأرز والبصل مع زيت الزيتون البكر وعصير الليمون الحامض. وصفة تقليدية تُعدّ يومياً بأيادي أسرة الزهراني. خالٍ من المواد الحافظة، صحي ولذيذ.',
    descriptionEn: 'Fresh grape leaves stuffed with rice and onion in extra virgin olive oil and lemon juice. A traditional recipe prepared daily by the Al-Zahrani family. Preservative-free, healthy and delicious.',
    weight: '500 جرام (~25 قطعة)',
    weightEn: '500g (~25 pieces)',
    preparationTime: 'يُعدّ صباحاً',
    preparationTimeEn: 'Prepared in the morning',
    partnerSince: 'مارس 2022',
    partnerSinceEn: 'March 2022',
    stock: 8,
    certifications: ['طبيعي', 'خالٍ من المواد الحافظة'],
    certificationsEn: ['Halal', 'Natural', 'Preservative-free'],
    orderCutoff: '21:00',
    whatsapp: '+966501111001',
    sizes: [
      { id: 'sm', label: 'حجم صغير (250 جرام)', labelEn: 'Small (250g)',    priceAdj: -18 },
      { id: 'md', label: 'حجم متوسط (500 جرام)', labelEn: 'Medium (500g)',  priceAdj: 0  },
      { id: 'lg', label: 'حجم كبير (1 كيلو)',    labelEn: 'Large (1kg)',    priceAdj: 45 },
    ],
    colors: null,
    isRefundable: false,
    refundPolicy: 'المنتجات الطازجة لا تُستبدل ولا تُرجع بعد التسليم. في حال وجود خلل واضح في المنتج عند الاستلام، يُرجى التواصل مع البائع فوراً وإرفاق صورة.',
    refundPolicyEn: 'Fresh products cannot be exchanged or returned after delivery. If there is a clear defect in the product upon receipt, please contact the seller immediately and attach a photo.',
    specifications: {
      'المكونات':    'ورق عنب، أرز، زيت زيتون بكر، ليمون، بصل، ملح وبهارات',
      'الوزن':       '500 جرام (~25 قطعة)',
      'الحصص':       '3-4 أشخاص',
      'التخزين':     'في الثلاجة، يستهلك خلال 48 ساعة',
      'مواد حافظة':  'خالٍ من المواد الحافظة',
      'يحتوي على':   'زيت زيتون، أرز (خالٍ من الجلوتين)',
    },
    specificationsEn: {
      'Ingredients':  'Grape leaves, rice, extra virgin olive oil, lemon, onion, salt and spices',
      'Weight':       '500g (~25 pieces)',
      'Servings':     '3-4 people',
      'Storage':      'Refrigerated, consume within 48 hours',
      'Preservatives':'Preservative-free',
      'Contains':     'Olive oil, rice (gluten-free)',
    },
  },
  {
    id: 2,
    name: 'كيكة الليمون بالقشطة الطازجة',
    nameEn: 'Lemon Cream Cake',
    family: 'أسرة الغامدي',
    familyEn: 'Al-Ghamdi Family',
    sellerCity: 'جدة',
    sellerCityEn: 'Jeddah',
    price: 85,
    originalPrice: null,
    rating: 4.9,
    reviews: 203,
    badge: 'جديد',
    badgeEn: 'New',
    badgeColor: 'bg-blue-500',
    emoji: '🍋',
    images: ['🍋', '🎂', '🍰', '🧁', '🫙'],
    gradient: 'from-yellow-200 to-amber-100',
    isPerishable: true,
    deliveryType: 'local',
    description: 'كيكة ليمون طرية بطعم حامض منعش مع طبقة قشطة طازجة كريمية. تُخبز بالزبدة الطبيعية ودقيق القمح الأبيض. مثالية للمناسبات والتجمعات العائلية.',
    descriptionEn: 'Soft lemon cake with a refreshing tang and a rich fresh cream layer. Baked with natural butter and white wheat flour. Perfect for occasions and family gatherings.',
    weight: 'قالب كامل (~8 قطع)',
    weightEn: 'Full tray (~8 pieces)',
    preparationTime: 'تُخبز عند الطلب',
    preparationTimeEn: 'Baked to order',
    partnerSince: 'يوليو 2023',
    partnerSinceEn: 'July 2023',
    stock: 3,
    orderCutoff: '20:00',
    whatsapp: '+966501111002',
    sizes: [
      { id: 'half',   label: 'نصف قالب',  labelEn: 'Half Tray',    priceAdj: -35 },
      { id: 'full',   label: 'قالب كامل', labelEn: 'Full Tray',    priceAdj: 0   },
      { id: 'double', label: 'قالبان',    labelEn: 'Two Trays',    priceAdj: 80  },
    ],
    colors: [
      { id: 'lemon',      label: 'ليمون',     labelEn: 'Lemon',      hex: '#FDE68A' },
      { id: 'strawberry', label: 'فراولة',    labelEn: 'Strawberry', hex: '#FB7185' },
      { id: 'chocolate',  label: 'شوكولاتة', labelEn: 'Chocolate',  hex: '#78350F' },
    ],
    isRefundable: false,
    refundPolicy: 'المخبوزات الطازجة لا تُستبدل ولا تُرجع. في حال وجود خلل في المنتج، تواصل مع البائع خلال ساعة من الاستلام مع إرفاق صورة.',
    refundPolicyEn: 'Fresh baked goods cannot be exchanged or returned. If there is a defect, contact the seller within one hour of receipt with a photo.',
    specifications: {
      'المكونات':    'دقيق، بيض، زبدة طبيعية، سكر، ليمون، قشطة طازجة',
      'الحجم':       'قالب 24×24 سم',
      'الحصص':       '8-10 أشخاص',
      'التخزين':     'في الثلاجة، يستهلك خلال 24 ساعة',
      'يحتوي على':   'جلوتين، بيض، منتجات الألبان',
      'مواد حافظة':  'خالٍ من المواد الحافظة',
    },
    specificationsEn: {
      'Ingredients':  'Flour, eggs, natural butter, sugar, lemon, fresh cream',
      'Size':         '24×24 cm tray',
      'Servings':     '8-10 people',
      'Storage':      'Refrigerated, consume within 24 hours',
      'Contains':     'Gluten, eggs, dairy',
      'Preservatives':'Preservative-free',
    },
  },
  {
    id: 7,
    name: 'مكرونة بالدجاج المنزلية الطازجة',
    nameEn: 'Fresh Homemade Chicken Pasta',
    family: 'أسرة السلمي',
    familyEn: 'Al-Salmi Family',
    sellerCity: 'جدة',
    sellerCityEn: 'Jeddah',
    price: 55,
    originalPrice: null,
    rating: 4.8,
    reviews: 94,
    badge: 'طازج يومياً',
    badgeEn: 'Daily Fresh',
    badgeColor: 'bg-emerald-500',
    emoji: '🍝',
    images: ['🍝', '🍗', '🧅', '🫙', '🌿'],
    gradient: 'from-red-100 to-orange-50',
    isPerishable: true,
    deliveryType: 'local',
    description: 'مكرونة إيطالية منزلية مطبوخة بصدر دجاج طازج وصلصة طماطم بيتية مع توابل منزلية خاصة. كل قدر يُعدّ بحب وعناية من أسرة السلمي.',
    descriptionEn: 'Homemade Italian pasta cooked with fresh chicken breast and homemade tomato sauce with special home spices. Each pot is prepared with love and care by the Al-Salmi family.',
    weight: 'وجبة لـ 2-3 أشخاص',
    weightEn: 'Meal for 2-3 people',
    preparationTime: 'طازجة يومياً',
    preparationTimeEn: 'Fresh daily',
    partnerSince: 'نوفمبر 2023',
    partnerSinceEn: 'November 2023',
    stock: 15,
    certifications: ['طازج يومياً'],
    certificationsEn: ['Halal', 'Daily Fresh'],
    orderCutoff: '21:00',
    whatsapp: '+966501111007',
    sizes: [
      { id: 'sm', label: 'حجم فردي (400 جرام)',     labelEn: 'Single (400g)',    priceAdj: -25 },
      { id: 'md', label: 'حجم عائلي (800 جرام)',     labelEn: 'Family (800g)',    priceAdj: 0   },
      { id: 'lg', label: 'حجم الحفلات (1.5 كيلو)',  labelEn: 'Party (1.5kg)',    priceAdj: 55  },
    ],
    colors: null,
    isRefundable: false,
    refundPolicy: 'الأطباق الطازجة لا تُستبدل ولا تُرجع. في حال وجود مشكلة، تواصل مع البائع فوراً بعد الاستلام مع إرفاق صورة توضيحية.',
    refundPolicyEn: 'Fresh dishes cannot be exchanged or returned. If there is an issue, contact the seller immediately after receipt with a photo.',
    specifications: {
      'المكونات':    'مكرونة، دجاج طازج، طماطم، بصل، ثوم، توابل منزلية',
      'الوزن':       '~800 جرام',
      'الحصص':       '2-3 أشخاص',
      'التخزين':     'في الثلاجة، يستهلك خلال 24 ساعة',
      'يحتوي على':   'جلوتين، دواجن',
      'مواد حافظة':  'خالٍ من المواد الحافظة',
    },
    specificationsEn: {
      'Ingredients':  'Pasta, fresh chicken, tomatoes, onion, garlic, home spices',
      'Weight':       '~800g',
      'Servings':     '2-3 people',
      'Storage':      'Refrigerated, consume within 24 hours',
      'Contains':     'Gluten, poultry',
      'Preservatives':'Preservative-free',
    },
  },
  {
    id: 8,
    name: 'صمون منزلي بالسمسم والزعتر',
    nameEn: 'Homemade Sesame & Thyme Bread',
    family: 'أسرة الحربي',
    familyEn: 'Al-Harbi Family',
    sellerCity: 'الرياض',
    sellerCityEn: 'Riyadh',
    price: 28,
    originalPrice: null,
    rating: 4.7,
    reviews: 143,
    badge: 'طازج اليوم',
    badgeEn: 'Fresh Today',
    badgeColor: 'bg-amber-500',
    emoji: '🫓',
    images: ['🫓', '🌾', '🫒', '🌿', '🧄'],
    gradient: 'from-amber-100 to-yellow-50',
    isPerishable: true,
    deliveryType: 'local',
    description: 'خبز صمون منزلي مقرمش من الخارج وطري من الداخل، مرش بالسمسم المحمص والزعتر الأخضر. يُخبز على الطريقة التقليدية في الفرن.',
    descriptionEn: 'Homemade bread, crispy on the outside and soft on the inside, sprinkled with toasted sesame and fresh thyme. Baked the traditional way in the oven.',
    weight: '6 أرغفة',
    weightEn: '6 loaves',
    preparationTime: 'يُخبز صباحاً',
    preparationTimeEn: 'Baked in the morning',
    partnerSince: 'يناير 2022',
    partnerSinceEn: 'January 2022',
    stock: 20,
    certifications: ['طازج يومياً'],
    certificationsEn: ['Halal', 'Daily Fresh'],
    orderCutoff: '21:00',
    whatsapp: '+966501111008',
    sizes: [
      { id: 'sm', label: '3 أرغفة',    labelEn: '3 loaves',    priceAdj: -14 },
      { id: 'md', label: '6 أرغفة',    labelEn: '6 loaves',    priceAdj: 0   },
      { id: 'lg', label: '12 رغيفاً',  labelEn: '12 loaves',   priceAdj: 22  },
    ],
    colors: null,
    isRefundable: false,
    refundPolicy: 'المخبوزات الطازجة لا تُستبدل ولا تُرجع. في حال وجود خلل في المنتج، تواصل مع البائع فوراً.',
    refundPolicyEn: 'Fresh baked goods cannot be exchanged or returned. If there is a defect, contact the seller immediately.',
    specifications: {
      'المكونات':        'دقيق قمح، خميرة، سمسم، زعتر، ملح، زيت نباتي',
      'العدد':           '6 أرغفة',
      'الوزن الإجمالي': '~420 جرام',
      'التخزين':         'يوم واحد بالحرارة العادية أو أسبوعين في الفريزر',
      'يحتوي على':       'جلوتين، سمسم',
      'مواد حافظة':      'خالٍ من المواد الحافظة',
    },
    specificationsEn: {
      'Ingredients':  'Wheat flour, yeast, sesame, thyme, salt, vegetable oil',
      'Count':        '6 loaves',
      'Total Weight': '~420g',
      'Storage':      '1 day at room temp or 2 weeks frozen',
      'Contains':     'Gluten, sesame',
      'Preservatives':'Preservative-free',
    },
  },
  // ── Non-Perishable · ships nationwide ─────────────────────────────────────
  {
    id: 3,
    name: 'بهارات القصيم الأصيلة',
    nameEn: 'Al-Qassim Authentic Spice Blend',
    family: 'أسرة العنزي',
    familyEn: 'Al-Anazi Family',
    sellerCity: 'بريدة',
    sellerCityEn: 'Buraydah',
    price: 30,
    originalPrice: 38,
    rating: 4.7,
    reviews: 89,
    badge: 'خصم 21%',
    badgeEn: '21% Off',
    badgeColor: 'bg-red-500',
    emoji: '🌶️',
    images: ['🌶️', '🫙', '🌿', '🧄', '🫚'],
    gradient: 'from-orange-200 to-red-100',
    isPerishable: false,
    deliveryType: 'nationwide',
    description: 'خلطة بهارات أصيلة من القصيم مكوّنة من أكثر من 12 نوعاً من التوابل المختارة يدوياً. تُضاف للكبسة والمندي وسائر المطبخ النجدي لإضفاء نكهة أصيلة لا تُنسى.',
    descriptionEn: 'Authentic spice blend from Qassim made of more than 12 hand-selected spice varieties. Added to Kabsa, Mandi, and other Najdi dishes for an unforgettable authentic flavor.',
    weight: '250 جرام',
    weightEn: '250g',
    preparationTime: 'تُحضّر وتُطحن عند الطلب',
    preparationTimeEn: 'Prepared and ground to order',
    partnerSince: 'أبريل 2021',
    partnerSinceEn: 'April 2021',
    stock: 45,
    certifications: ['طبيعي', 'خالٍ من المنكهات الصناعية'],
    certificationsEn: ['Halal', 'Natural', 'No Artificial Flavors'],
    orderCutoff: null,
    whatsapp: '+966501111003',
    sizes: [
      { id: 'sm', label: '100 جرام', labelEn: '100g', priceAdj: -12 },
      { id: 'md', label: '250 جرام', labelEn: '250g', priceAdj: 0   },
      { id: 'lg', label: '500 جرام', labelEn: '500g', priceAdj: 28  },
    ],
    colors: null,
    isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتج خلال 7 أيام من تاريخ الاستلام إذا كان مغلقاً ولم يُفتح، مع الاحتفاظ بالفاتورة الأصلية.',
    refundPolicyEn: 'The product can be returned within 7 days of receipt if it is sealed and unopened, with the original invoice retained.',
    specifications: {
      'المكونات':       'خلطة من 12+ نوع من التوابل المختارة',
      'الوزن':          '250 جرام',
      'الصلاحية':       '12 شهراً من تاريخ التحضير',
      'مستوى الحرارة':  'متوسط',
      'مناسب لـ':       'الكبسة، المندي، الأرز، اللحم',
      'التغليف':        'برطمان زجاجي محكم الإغلاق',
    },
    specificationsEn: {
      'Ingredients':    '12+ types of hand-selected spices',
      'Weight':         '250g',
      'Shelf Life':     '12 months from preparation date',
      'Heat Level':     'Medium',
      'Suitable for':   'Kabsa, Mandi, rice, meat',
      'Packaging':      'Airtight glass jar',
    },
  },
  {
    id: 4,
    name: 'عسل السدر الجبلي الطبيعي',
    nameEn: 'Natural Mountain Sidr Honey',
    family: 'أسرة القحطاني',
    familyEn: 'Al-Qahtani Family',
    sellerCity: 'الباحة',
    sellerCityEn: 'Al Baha',
    price: 180,
    originalPrice: null,
    rating: 5.0,
    reviews: 341,
    badge: 'مميز',
    badgeEn: 'Premium',
    badgeColor: 'bg-emerald-600',
    emoji: '🍯',
    images: ['🍯', '🐝', '🌸', '🌳', '🫙'],
    gradient: 'from-amber-200 to-yellow-100',
    isPerishable: false,
    deliveryType: 'nationwide',
    description: 'عسل سدر جبلي نقي 100% من مناحل أسرة القحطاني في جبال الباحة. يُجمع يدوياً مرة واحدة في السنة. غني بالمضادات الحيوية الطبيعية ومفيد جداً للصحة.',
    descriptionEn: '100% pure mountain sidr honey from Al-Qahtani family apiaries in the Al Baha mountains. Hand-harvested once a year. Rich in natural antibiotics and highly beneficial for health.',
    weight: '500 جرام',
    weightEn: '500g',
    preparationTime: 'طبيعي · معالج بدون حرارة',
    preparationTimeEn: 'Natural · cold-processed',
    partnerSince: 'ديسمبر 2020',
    partnerSinceEn: 'December 2020',
    stock: 12,
    certifications: ['عضوي', 'غير معالج بالحرارة', 'خالٍ من المواد الحافظة'],
    certificationsEn: ['Halal', 'Organic', 'Raw (Unheated)', 'Preservative-free'],
    orderCutoff: null,
    whatsapp: '+966501111004',
    sizes: [
      { id: 'sm', label: '250 جرام',    labelEn: '250g',       priceAdj: -80  },
      { id: 'md', label: '500 جرام',    labelEn: '500g',       priceAdj: 0    },
      { id: 'lg', label: 'كيلو كامل',  labelEn: '1kg full',   priceAdj: 150  },
    ],
    colors: null,
    isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتج خلال 14 يوماً من الاستلام إذا كان مغلقاً وغير مستخدم، مع الاحتفاظ بالفاتورة.',
    refundPolicyEn: 'The product can be returned within 14 days of receipt if it is sealed and unused, with the original invoice retained.',
    specifications: {
      'النوع':              'سدر جبلي طبيعي 100%',
      'الوزن':              '500 جرام',
      'الصلاحية':           'سنتان من تاريخ التعبئة',
      'منطقة الجمع':        'جبال الباحة، المرتفعات الجنوبية',
      'طريقة المعالجة':     'عسل خام بدون تسخين',
      'التغليف':            'برطمان زجاجي فاخر',
    },
    specificationsEn: {
      'Type':             '100% natural mountain sidr',
      'Weight':           '500g',
      'Shelf Life':       '2 years from fill date',
      'Harvest Region':   'Al Baha Mountains, Southern Highlands',
      'Processing':       'Raw honey, no heating',
      'Packaging':        'Premium glass jar',
    },
  },
  {
    id: 5,
    name: 'حلوى التمر بالمكسرات الفاخرة',
    nameEn: 'Premium Date Candy with Luxury Nuts',
    family: 'أسرة الدوسري',
    familyEn: 'Al-Dosari Family',
    sellerCity: 'الأحساء',
    sellerCityEn: 'Al-Ahsa',
    price: 60,
    originalPrice: null,
    rating: 4.6,
    reviews: 156,
    badge: null,
    badgeEn: null,
    emoji: '🌴',
    images: ['🌴', '🥜', '🫙', '🍫', '🌰'],
    gradient: 'from-stone-200 to-amber-100',
    isPerishable: false,
    deliveryType: 'nationwide',
    description: 'حلوى تمر فاخرة من أجود تمور الأحساء، محشوة بالمكسرات المتنوعة كاللوز والجوز والكاجو. تُعدّ يدوياً بطريقة تقليدية متوارثة عبر الأجيال.',
    descriptionEn: 'Luxury date candy from the finest Al-Ahsa dates, stuffed with assorted nuts including almonds, walnuts, and cashews. Handcrafted in a traditional method passed down through generations.',
    weight: '400 جرام (~20 قطعة)',
    weightEn: '400g (~20 pieces)',
    preparationTime: 'تُجهّز عند الطلب',
    preparationTimeEn: 'Prepared to order',
    partnerSince: 'أغسطس 2022',
    partnerSinceEn: 'August 2022',
    stock: 28,
    certifications: ['طبيعي', 'منتج الأحساء'],
    certificationsEn: ['Halal', 'Natural', 'Al-Ahsa Product'],
    orderCutoff: null,
    whatsapp: '+966501111005',
    sizes: [
      { id: 'sm', label: '200 جرام (~10 قطع)',   labelEn: '200g (~10 pcs)',    priceAdj: -25 },
      { id: 'md', label: '400 جرام (~20 قطعة)',  labelEn: '400g (~20 pcs)',    priceAdj: 0   },
      { id: 'lg', label: '800 جرام (~40 قطعة)', labelEn: '800g (~40 pcs)',    priceAdj: 50  },
    ],
    colors: [
      { id: 'gold',  label: 'علبة ذهبية',  labelEn: 'Gold Box',   hex: '#C9A84C' },
      { id: 'brown', label: 'علبة بني',    labelEn: 'Brown Box',  hex: '#7B3F00' },
      { id: 'green', label: 'علبة خضراء', labelEn: 'Green Box',  hex: '#1C5C2E' },
    ],
    isRefundable: true,
    refundPolicy: 'يمكن إرجاع علب الهدايا غير المفتوحة خلال 7 أيام من الاستلام. المنتجات المفتوحة لا تُرجع.',
    refundPolicyEn: 'Unopened gift boxes can be returned within 7 days of receipt. Opened products cannot be returned.',
    specifications: {
      'المكونات':  'تمر عجوة، لوز، جوز، كاجو، هيل',
      'الوزن':     '400 جرام (~20 قطعة)',
      'الصلاحية':  '3 أشهر في درجة الحرارة العادية',
      'يحتوي على': 'مكسرات متنوعة',
      'التغليف':   'علبة هدايا فاخرة (اختيار اللون متاح)',
      'مناسب لـ':  'الهدايا، المناسبات، المجالس',
    },
    specificationsEn: {
      'Ingredients':  'Ajwa dates, almonds, walnuts, cashews, cardamom',
      'Weight':       '400g (~20 pieces)',
      'Shelf Life':   '3 months at room temperature',
      'Contains':     'Assorted nuts',
      'Packaging':    'Luxury gift box (color choice available)',
      'Suitable for': 'Gifts, occasions, gatherings',
    },
  },
  {
    id: 6,
    name: 'مربى التين البلدي المنزلية',
    nameEn: 'Homemade Wild Fig Jam',
    family: 'أسرة الشمري',
    familyEn: 'Al-Shamri Family',
    sellerCity: 'حائل',
    sellerCityEn: "Ha'il",
    price: 35,
    originalPrice: null,
    rating: 4.5,
    reviews: 78,
    badge: null,
    badgeEn: null,
    emoji: '🫐',
    images: ['🫐', '🍯', '🫙', '🌿', '🍞'],
    gradient: 'from-purple-200 to-violet-100',
    isPerishable: false,
    deliveryType: 'nationwide',
    description: 'مربى تين بلدي منزلية مصنوعة من ثمار التين الطازجة المقطوفة من بساتين حائل. تُطهى ببطء مع السكر الطبيعي دون أي مواد حافظة أو مضافات صناعية.',
    descriptionEn: 'Homemade wild fig jam made from fresh figs harvested from Ha\'il orchards. Slow-cooked with natural sugar without any preservatives or artificial additives.',
    weight: '350 جرام',
    weightEn: '350g',
    preparationTime: 'تُعدّ موسمياً',
    preparationTimeEn: 'Prepared seasonally',
    partnerSince: 'مايو 2023',
    partnerSinceEn: 'May 2023',
    stock: 35,
    certifications: ['طبيعي', 'خالٍ من المواد الحافظة'],
    certificationsEn: ['Halal', 'Natural', 'Preservative-free'],
    orderCutoff: null,
    whatsapp: '+966501111006',
    sizes: [
      { id: 'sm', label: '200 جرام', labelEn: '200g', priceAdj: -12 },
      { id: 'md', label: '350 جرام', labelEn: '350g', priceAdj: 0   },
      { id: 'lg', label: '700 جرام', labelEn: '700g', priceAdj: 28  },
    ],
    colors: [
      { id: 'fig',     label: 'تين بلدي',  labelEn: 'Wild Fig',    hex: '#6D28D9' },
      { id: 'apricot', label: 'مشمش',      labelEn: 'Apricot',     hex: '#D97706' },
      { id: 'berry',   label: 'توت أحمر',  labelEn: 'Red Berry',   hex: '#BE185D' },
    ],
    isRefundable: true,
    refundPolicy: 'يمكن إرجاع البرطمانات غير المفتوحة خلال 14 يوماً من الاستلام مع الاحتفاظ بالفاتورة. البرطمانات المفتوحة لا تُرجع.',
    refundPolicyEn: 'Unopened jars can be returned within 14 days of receipt with the original invoice. Opened jars cannot be returned.',
    specifications: {
      'المكونات':   'تين بلدي طازج، سكر طبيعي، ليمون',
      'الوزن':      '350 جرام',
      'الصلاحية':   '6 أشهر بعد الفتح في الثلاجة',
      'نسبة السكر': '~55%',
      'التغليف':    'برطمان زجاجي محكم الإغلاق',
      'مواد حافظة': 'خالٍ من المواد الحافظة',
    },
    specificationsEn: {
      'Ingredients':  'Fresh wild figs, natural sugar, lemon',
      'Weight':       '350g',
      'Shelf Life':   '6 months after opening, refrigerated',
      'Sugar Content':'~55%',
      'Packaging':    'Airtight glass jar',
      'Preservatives':'Preservative-free',
    },
  },
];
