export const PRODUCTS = [
  // ── Perishable · local delivery only ─────────────────────────────────────
  {
    id: 1,
    name: 'ورق عنب بالزيت والليمون',
    family: 'أسرة الزهراني',
    sellerCity: 'الرياض',
    price: 45,
    originalPrice: null,
    rating: 4.8,
    reviews: 127,
    badge: 'الأكثر مبيعاً',
    badgeColor: 'bg-amber-500',
    emoji: '🍇',
    images: ['🍇', '🫙', '🌿', '🫚', '🍋'],
    gradient: 'from-green-200 to-emerald-100',
    isPerishable: true,
    deliveryType: 'local',
    description: 'ورق عنب طازج محشو بالأرز والبصل مع زيت الزيتون البكر وعصير الليمون الحامض. وصفة تقليدية تُعدّ يومياً بأيادي أسرة الزهراني. خالٍ من المواد الحافظة، صحي ولذيذ.',
    weight: '500 جرام (~25 قطعة)',
    preparationTime: 'يُعدّ صباحاً',
    partnerSince: 'مارس 2022',
    stock: 8,
    certifications: ['حلال', 'طبيعي', 'خالٍ من المواد الحافظة'],
    orderCutoff: '21:00',
    whatsapp: '+966501111001',
    sizes: [
      { id: 'sm', label: 'حجم صغير (250 جرام)', priceAdj: -18 },
      { id: 'md', label: 'حجم متوسط (500 جرام)', priceAdj: 0  },
      { id: 'lg', label: 'حجم كبير (1 كيلو)',    priceAdj: 45 },
    ],
    colors: null,
    isRefundable: false,
    refundPolicy: 'المنتجات الطازجة لا تُستبدل ولا تُرجع بعد التسليم. في حال وجود خلل واضح في المنتج عند الاستلام، يُرجى التواصل مع البائع فوراً وإرفاق صورة.',
    specifications: {
      'المكونات':    'ورق عنب، أرز، زيت زيتون بكر، ليمون، بصل، ملح وبهارات',
      'الوزن':       '500 جرام (~25 قطعة)',
      'الحصص':       '3-4 أشخاص',
      'التخزين':     'في الثلاجة، يستهلك خلال 48 ساعة',
      'مواد حافظة':  'خالٍ من المواد الحافظة',
      'يحتوي على':   'زيت زيتون، أرز (خالٍ من الجلوتين)',
    },
  },
  {
    id: 2,
    name: 'كيكة الليمون بالقشطة الطازجة',
    family: 'أسرة الغامدي',
    sellerCity: 'جدة',
    price: 85,
    originalPrice: null,
    rating: 4.9,
    reviews: 203,
    badge: 'جديد',
    badgeColor: 'bg-blue-500',
    emoji: '🍋',
    images: ['🍋', '🎂', '🍰', '🧁', '🫙'],
    gradient: 'from-yellow-200 to-amber-100',
    isPerishable: true,
    deliveryType: 'local',
    description: 'كيكة ليمون طرية بطعم حامض منعش مع طبقة قشطة طازجة كريمية. تُخبز بالزبدة الطبيعية ودقيق القمح الأبيض. مثالية للمناسبات والتجمعات العائلية.',
    weight: 'قالب كامل (~8 قطع)',
    preparationTime: 'تُخبز عند الطلب',
    partnerSince: 'يوليو 2023',
    stock: 3,
    certifications: ['حلال'],
    orderCutoff: '20:00',
    whatsapp: '+966501111002',
    sizes: [
      { id: 'half',   label: 'نصف قالب',  priceAdj: -35 },
      { id: 'full',   label: 'قالب كامل', priceAdj: 0   },
      { id: 'double', label: 'قالبان',    priceAdj: 80  },
    ],
    colors: [
      { id: 'lemon',     label: 'ليمون',      hex: '#FDE68A' },
      { id: 'strawberry',label: 'فراولة',     hex: '#FB7185' },
      { id: 'chocolate', label: 'شوكولاتة',  hex: '#78350F' },
    ],
    isRefundable: false,
    refundPolicy: 'المخبوزات الطازجة لا تُستبدل ولا تُرجع. في حال وجود خلل في المنتج، تواصل مع البائع خلال ساعة من الاستلام مع إرفاق صورة.',
    specifications: {
      'المكونات':    'دقيق، بيض، زبدة طبيعية، سكر، ليمون، قشطة طازجة',
      'الحجم':       'قالب 24×24 سم',
      'الحصص':       '8-10 أشخاص',
      'التخزين':     'في الثلاجة، يستهلك خلال 24 ساعة',
      'يحتوي على':   'جلوتين، بيض، منتجات الألبان',
      'مواد حافظة':  'خالٍ من المواد الحافظة',
    },
  },
  {
    id: 7,
    name: 'مكرونة بالدجاج المنزلية الطازجة',
    family: 'أسرة السلمي',
    sellerCity: 'جدة',
    price: 55,
    originalPrice: null,
    rating: 4.8,
    reviews: 94,
    badge: 'طازج يومياً',
    badgeColor: 'bg-emerald-500',
    emoji: '🍝',
    images: ['🍝', '🍗', '🧅', '🫙', '🌿'],
    gradient: 'from-red-100 to-orange-50',
    isPerishable: true,
    deliveryType: 'local',
    description: 'مكرونة إيطالية منزلية مطبوخة بصدر دجاج طازج وصلصة طماطم بيتية مع توابل منزلية خاصة. كل قدر يُعدّ بحب وعناية من أسرة السلمي.',
    weight: 'وجبة لـ 2-3 أشخاص',
    preparationTime: 'طازجة يومياً',
    partnerSince: 'نوفمبر 2023',
    stock: 15,
    certifications: ['حلال', 'طازج يومياً'],
    orderCutoff: '21:00',
    whatsapp: '+966501111007',
    sizes: [
      { id: 'sm', label: 'حجم فردي (400 جرام)',      priceAdj: -25 },
      { id: 'md', label: 'حجم عائلي (800 جرام)',      priceAdj: 0   },
      { id: 'lg', label: 'حجم الحفلات (1.5 كيلو)',   priceAdj: 55  },
    ],
    colors: null,
    isRefundable: false,
    refundPolicy: 'الأطباق الطازجة لا تُستبدل ولا تُرجع. في حال وجود مشكلة، تواصل مع البائع فوراً بعد الاستلام مع إرفاق صورة توضيحية.',
    specifications: {
      'المكونات':    'مكرونة، دجاج طازج، طماطم، بصل، ثوم، توابل منزلية',
      'الوزن':       '~800 جرام',
      'الحصص':       '2-3 أشخاص',
      'التخزين':     'في الثلاجة، يستهلك خلال 24 ساعة',
      'يحتوي على':   'جلوتين، دواجن',
      'مواد حافظة':  'خالٍ من المواد الحافظة',
    },
  },
  {
    id: 8,
    name: 'صمون منزلي بالسمسم والزعتر',
    family: 'أسرة الحربي',
    sellerCity: 'الرياض',
    price: 28,
    originalPrice: null,
    rating: 4.7,
    reviews: 143,
    badge: 'طازج اليوم',
    badgeColor: 'bg-amber-500',
    emoji: '🫓',
    images: ['🫓', '🌾', '🫒', '🌿', '🧄'],
    gradient: 'from-amber-100 to-yellow-50',
    isPerishable: true,
    deliveryType: 'local',
    description: 'خبز صمون منزلي مقرمش من الخارج وطري من الداخل، مرش بالسمسم المحمص والزعتر الأخضر. يُخبز على الطريقة التقليدية في الفرن.',
    weight: '6 أرغفة',
    preparationTime: 'يُخبز صباحاً',
    partnerSince: 'يناير 2022',
    stock: 20,
    certifications: ['حلال', 'طازج يومياً'],
    orderCutoff: '21:00',
    whatsapp: '+966501111008',
    sizes: [
      { id: 'sm', label: '3 أرغفة',   priceAdj: -14 },
      { id: 'md', label: '6 أرغفة',   priceAdj: 0   },
      { id: 'lg', label: '12 رغيفاً', priceAdj: 22  },
    ],
    colors: null,
    isRefundable: false,
    refundPolicy: 'المخبوزات الطازجة لا تُستبدل ولا تُرجع. في حال وجود خلل في المنتج، تواصل مع البائع فوراً.',
    specifications: {
      'المكونات':    'دقيق قمح، خميرة، سمسم، زعتر، ملح، زيت نباتي',
      'العدد':       '6 أرغفة',
      'الوزن الإجمالي': '~420 جرام',
      'التخزين':     'يوم واحد بالحرارة العادية أو أسبوعين في الفريزر',
      'يحتوي على':   'جلوتين، سمسم',
      'مواد حافظة':  'خالٍ من المواد الحافظة',
    },
  },
  // ── Non-Perishable · ships nationwide ─────────────────────────────────────
  {
    id: 3,
    name: 'بهارات القصيم الأصيلة',
    family: 'أسرة العنزي',
    sellerCity: 'بريدة',
    price: 30,
    originalPrice: 38,
    rating: 4.7,
    reviews: 89,
    badge: 'خصم 21%',
    badgeColor: 'bg-red-500',
    emoji: '🌶️',
    images: ['🌶️', '🫙', '🌿', '🧄', '🫚'],
    gradient: 'from-orange-200 to-red-100',
    isPerishable: false,
    deliveryType: 'nationwide',
    description: 'خلطة بهارات أصيلة من القصيم مكوّنة من أكثر من 12 نوعاً من التوابل المختارة يدوياً. تُضاف للكبسة والمندي وسائر المطبخ النجدي لإضفاء نكهة أصيلة لا تُنسى.',
    weight: '250 جرام',
    preparationTime: 'تُحضّر وتُطحن عند الطلب',
    partnerSince: 'أبريل 2021',
    stock: 45,
    certifications: ['حلال', 'طبيعي', 'خالٍ من المنكهات الصناعية'],
    orderCutoff: null,
    whatsapp: '+966501111003',
    sizes: [
      { id: 'sm', label: '100 جرام', priceAdj: -12 },
      { id: 'md', label: '250 جرام', priceAdj: 0   },
      { id: 'lg', label: '500 جرام', priceAdj: 28  },
    ],
    colors: null,
    isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتج خلال 7 أيام من تاريخ الاستلام إذا كان مغلقاً ولم يُفتح، مع الاحتفاظ بالفاتورة الأصلية.',
    specifications: {
      'المكونات':    'خلطة من 12+ نوع من التوابل المختارة',
      'الوزن':       '250 جرام',
      'الصلاحية':    '12 شهراً من تاريخ التحضير',
      'مستوى الحرارة': 'متوسط',
      'مناسب لـ':    'الكبسة، المندي، الأرز، اللحم',
      'التغليف':     'برطمان زجاجي محكم الإغلاق',
    },
  },
  {
    id: 4,
    name: 'عسل السدر الجبلي الطبيعي',
    family: 'أسرة القحطاني',
    sellerCity: 'الباحة',
    price: 180,
    originalPrice: null,
    rating: 5.0,
    reviews: 341,
    badge: 'مميز',
    badgeColor: 'bg-emerald-600',
    emoji: '🍯',
    images: ['🍯', '🐝', '🌸', '🌳', '🫙'],
    gradient: 'from-amber-200 to-yellow-100',
    isPerishable: false,
    deliveryType: 'nationwide',
    description: 'عسل سدر جبلي نقي 100% من مناحل أسرة القحطاني في جبال الباحة. يُجمع يدوياً مرة واحدة في السنة. غني بالمضادات الحيوية الطبيعية ومفيد جداً للصحة.',
    weight: '500 جرام',
    preparationTime: 'طبيعي · معالج بدون حرارة',
    partnerSince: 'ديسمبر 2020',
    stock: 12,
    certifications: ['حلال', 'عضوي', 'غير معالج بالحرارة', 'خالٍ من المواد الحافظة'],
    orderCutoff: null,
    whatsapp: '+966501111004',
    sizes: [
      { id: 'sm', label: '250 جرام',     priceAdj: -80  },
      { id: 'md', label: '500 جرام',     priceAdj: 0    },
      { id: 'lg', label: 'كيلو كامل',   priceAdj: 150  },
    ],
    colors: null,
    isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتج خلال 14 يوماً من الاستلام إذا كان مغلقاً وغير مستخدم، مع الاحتفاظ بالفاتورة.',
    specifications: {
      'النوع':       'سدر جبلي طبيعي 100%',
      'الوزن':       '500 جرام',
      'الصلاحية':    'سنتان من تاريخ التعبئة',
      'منطقة الجمع': 'جبال الباحة، المرتفعات الجنوبية',
      'طريقة المعالجة': 'عسل خام بدون تسخين',
      'التغليف':     'برطمان زجاجي فاخر',
    },
  },
  {
    id: 5,
    name: 'حلوى التمر بالمكسرات الفاخرة',
    family: 'أسرة الدوسري',
    sellerCity: 'الأحساء',
    price: 60,
    originalPrice: null,
    rating: 4.6,
    reviews: 156,
    badge: null,
    emoji: '🌴',
    images: ['🌴', '🥜', '🫙', '🍫', '🌰'],
    gradient: 'from-stone-200 to-amber-100',
    isPerishable: false,
    deliveryType: 'nationwide',
    description: 'حلوى تمر فاخرة من أجود تمور الأحساء، محشوة بالمكسرات المتنوعة كاللوز والجوز والكاجو. تُعدّ يدوياً بطريقة تقليدية متوارثة عبر الأجيال.',
    weight: '400 جرام (~20 قطعة)',
    preparationTime: 'تُجهّز عند الطلب',
    partnerSince: 'أغسطس 2022',
    stock: 28,
    certifications: ['حلال', 'طبيعي', 'منتج الأحساء'],
    orderCutoff: null,
    whatsapp: '+966501111005',
    sizes: [
      { id: 'sm', label: '200 جرام (~10 قطع)',   priceAdj: -25 },
      { id: 'md', label: '400 جرام (~20 قطعة)',  priceAdj: 0   },
      { id: 'lg', label: '800 جرام (~40 قطعة)', priceAdj: 50  },
    ],
    colors: [
      { id: 'gold',  label: 'علبة ذهبية',  hex: '#C9A84C' },
      { id: 'brown', label: 'علبة بني',    hex: '#7B3F00' },
      { id: 'green', label: 'علبة خضراء', hex: '#1C5C2E' },
    ],
    isRefundable: true,
    refundPolicy: 'يمكن إرجاع علب الهدايا غير المفتوحة خلال 7 أيام من الاستلام. المنتجات المفتوحة لا تُرجع.',
    specifications: {
      'المكونات':    'تمر عجوة، لوز، جوز، كاجو، هيل',
      'الوزن':       '400 جرام (~20 قطعة)',
      'الصلاحية':    '3 أشهر في درجة الحرارة العادية',
      'يحتوي على':   'مكسرات متنوعة',
      'التغليف':     'علبة هدايا فاخرة (اختيار اللون متاح)',
      'مناسب لـ':    'الهدايا، المناسبات، المجالس',
    },
  },
  {
    id: 6,
    name: 'مربى التين البلدي المنزلية',
    family: 'أسرة الشمري',
    sellerCity: 'حائل',
    price: 35,
    originalPrice: null,
    rating: 4.5,
    reviews: 78,
    badge: null,
    emoji: '🫐',
    images: ['🫐', '🍯', '🫙', '🌿', '🍞'],
    gradient: 'from-purple-200 to-violet-100',
    isPerishable: false,
    deliveryType: 'nationwide',
    description: 'مربى تين بلدي منزلية مصنوعة من ثمار التين الطازجة المقطوفة من بساتين حائل. تُطهى ببطء مع السكر الطبيعي دون أي مواد حافظة أو مضافات صناعية.',
    weight: '350 جرام',
    preparationTime: 'تُعدّ موسمياً',
    partnerSince: 'مايو 2023',
    stock: 35,
    certifications: ['حلال', 'طبيعي', 'خالٍ من المواد الحافظة'],
    orderCutoff: null,
    whatsapp: '+966501111006',
    sizes: [
      { id: 'sm', label: '200 جرام', priceAdj: -12 },
      { id: 'md', label: '350 جرام', priceAdj: 0   },
      { id: 'lg', label: '700 جرام', priceAdj: 28  },
    ],
    colors: [
      { id: 'fig',     label: 'تين بلدي',  hex: '#6D28D9' },
      { id: 'apricot', label: 'مشمش',      hex: '#D97706' },
      { id: 'berry',   label: 'توت أحمر',  hex: '#BE185D' },
    ],
    isRefundable: true,
    refundPolicy: 'يمكن إرجاع البرطمانات غير المفتوحة خلال 14 يوماً من الاستلام مع الاحتفاظ بالفاتورة. البرطمانات المفتوحة لا تُرجع.',
    specifications: {
      'المكونات':    'تين بلدي طازج، سكر طبيعي، ليمون',
      'الوزن':       '350 جرام',
      'الصلاحية':    '6 أشهر بعد الفتح في الثلاجة',
      'نسبة السكر':  '~55%',
      'التغليف':     'برطمان زجاجي محكم الإغلاق',
      'مواد حافظة':  'خالٍ من المواد الحافظة',
    },
  },
];
