export const PRODUCTS = [

  // ══════════════════════════════════════════════════════════════════════════
  // FOOD — Perishable · Local Delivery
  // ══════════════════════════════════════════════════════════════════════════

  // ─── الرياض ───────────────────────────────────────────────────────────────

  {
    id: 1, category: 'food',
    name: 'ورق عنب بالزيت والليمون',
    nameEn: 'Stuffed Grape Leaves with Olive Oil & Lemon',
    family: 'أسرة الزهراني', familyEn: 'Al-Zahrani Family',
    sellerCity: 'الرياض', sellerCityEn: 'Riyadh',
    price: 45, originalPrice: null, rating: 4.8, reviews: 127,
    badge: 'الأكثر مبيعاً', badgeEn: 'Best Seller', badgeColor: 'bg-amber-500',
    emoji: '🍇', images: ['🍇', '🫙', '🌿', '🫚', '🍋'],
    gradient: 'from-green-200 to-emerald-100',
    isPerishable: true, deliveryType: 'local',
    description: 'ورق عنب طازج محشو بالأرز والبصل مع زيت الزيتون البكر وعصير الليمون الحامض. وصفة تقليدية تُعدّ يومياً بأيادي أسرة الزهراني. خالٍ من المواد الحافظة، صحي ولذيذ.',
    descriptionEn: 'Fresh grape leaves stuffed with rice and onion in extra virgin olive oil and lemon juice. A traditional recipe prepared daily by the Al-Zahrani family. Preservative-free, healthy and delicious.',
    weight: '500 جرام (~25 قطعة)', weightEn: '500g (~25 pieces)',
    preparationTime: 'يُعدّ صباحاً', preparationTimeEn: 'Prepared in the morning',
    partnerSince: 'مارس 2022', partnerSinceEn: 'March 2022',
    stock: 8, certifications: ['طبيعي', 'خالٍ من المواد الحافظة'],
    certificationsEn: ['Halal', 'Natural', 'Preservative-free'],
    orderCutoff: '21:00', whatsapp: '+966501111001',
    sizes: [
      { id: 'sm', label: 'حجم صغير (250 جرام)', labelEn: 'Small (250g)',  priceAdj: -18 },
      { id: 'md', label: 'حجم متوسط (500 جرام)', labelEn: 'Medium (500g)', priceAdj: 0  },
      { id: 'lg', label: 'حجم كبير (1 كيلو)',    labelEn: 'Large (1kg)',   priceAdj: 45 },
    ],
    colors: null, isRefundable: false,
    refundPolicy: 'المنتجات الطازجة لا تُستبدل ولا تُرجع بعد التسليم.',
    refundPolicyEn: 'Fresh products cannot be exchanged or returned after delivery.',
    specifications: { 'المكونات': 'ورق عنب، أرز، زيت زيتون بكر، ليمون، بصل، بهارات', 'الوزن': '500 جرام', 'الحصص': '3-4 أشخاص', 'التخزين': 'في الثلاجة، يستهلك خلال 48 ساعة' },
    specificationsEn: { 'Ingredients': 'Grape leaves, rice, olive oil, lemon, onion, spices', 'Weight': '500g', 'Servings': '3-4 people', 'Storage': 'Refrigerated, consume within 48 hours' },
  },

  {
    id: 8, category: 'food',
    name: 'صمون منزلي بالسمسم والزعتر',
    nameEn: 'Homemade Sesame & Thyme Bread',
    family: 'أسرة الحربي', familyEn: 'Al-Harbi Family',
    sellerCity: 'الرياض', sellerCityEn: 'Riyadh',
    price: 28, originalPrice: null, rating: 4.7, reviews: 143,
    badge: 'طازج اليوم', badgeEn: 'Fresh Today', badgeColor: 'bg-amber-500',
    emoji: '🫓', images: ['🫓', '🌾', '🫒', '🌿', '🧄'],
    gradient: 'from-amber-100 to-yellow-50',
    isPerishable: true, deliveryType: 'local',
    description: 'خبز صمون منزلي مقرمش من الخارج وطري من الداخل، مرش بالسمسم المحمص والزعتر الأخضر. يُخبز على الطريقة التقليدية في الفرن كل صباح.',
    descriptionEn: 'Homemade bread, crispy on the outside and soft on the inside, sprinkled with toasted sesame and fresh thyme. Baked the traditional way every morning.',
    weight: '6 أرغفة', weightEn: '6 loaves',
    preparationTime: 'يُخبز صباحاً', preparationTimeEn: 'Baked in the morning',
    partnerSince: 'يناير 2022', partnerSinceEn: 'January 2022',
    stock: 20, certifications: ['طازج يومياً'], certificationsEn: ['Halal', 'Daily Fresh'],
    orderCutoff: '21:00', whatsapp: '+966501111008',
    sizes: [
      { id: 'sm', label: '3 أرغفة',   labelEn: '3 loaves',  priceAdj: -14 },
      { id: 'md', label: '6 أرغفة',   labelEn: '6 loaves',  priceAdj: 0   },
      { id: 'lg', label: '12 رغيفاً', labelEn: '12 loaves', priceAdj: 22  },
    ],
    colors: null, isRefundable: false,
    refundPolicy: 'المخبوزات الطازجة لا تُستبدل ولا تُرجع.',
    refundPolicyEn: 'Fresh baked goods cannot be exchanged or returned.',
    specifications: { 'المكونات': 'دقيق قمح، خميرة، سمسم، زعتر، ملح، زيت نباتي', 'العدد': '6 أرغفة', 'التخزين': 'يوم واحد أو أسبوعين في الفريزر' },
    specificationsEn: { 'Ingredients': 'Wheat flour, yeast, sesame, thyme, salt, oil', 'Count': '6 loaves', 'Storage': '1 day or 2 weeks frozen' },
  },

  {
    id: 9, category: 'food',
    name: 'كبسة الدجاج المنزلية',
    nameEn: 'Homemade Chicken Kabsa',
    family: 'أسرة المطيري', familyEn: 'Al-Mutairi Family',
    sellerCity: 'الرياض', sellerCityEn: 'Riyadh',
    price: 65, originalPrice: null, rating: 4.9, reviews: 218,
    badge: 'الأكثر طلباً', badgeEn: 'Most Ordered', badgeColor: 'bg-emerald-500',
    emoji: '🍗', images: ['🍗', '🍚', '🌶️', '🧅', '🌿'],
    gradient: 'from-orange-100 to-amber-50',
    isPerishable: true, deliveryType: 'local',
    description: 'كبسة دجاج منزلية على أصول الطبخ النجدي الأصيل. أرز بسمتي مطبوخ بمرق الدجاج مع خلطة البهارات السرية لأسرة المطيري، يُقدَّم مع صلصة الدباء والمدعوس.',
    descriptionEn: 'Authentic Najdi-style homemade chicken Kabsa. Basmati rice cooked in chicken broth with the Al-Mutairi family\'s secret spice blend, served with pumpkin sauce and Madamous.',
    weight: 'وجبة لـ 3-4 أشخاص', weightEn: 'Meal for 3-4 people',
    preparationTime: 'تُطهى يومياً', preparationTimeEn: 'Cooked daily',
    partnerSince: 'فبراير 2021', partnerSinceEn: 'February 2021',
    stock: 10, certifications: ['حلال', 'طازج يومياً'], certificationsEn: ['Halal', 'Daily Fresh'],
    orderCutoff: '20:00', whatsapp: '+966501111009',
    sizes: [
      { id: 'sm', label: 'وجبة فردية',     labelEn: 'Single Meal',  priceAdj: -30 },
      { id: 'md', label: 'وجبة عائلية (4)', labelEn: 'Family (4)',   priceAdj: 0   },
      { id: 'lg', label: 'وجبة كبيرة (8)', labelEn: 'Large (8)',    priceAdj: 60  },
    ],
    colors: null, isRefundable: false,
    refundPolicy: 'الأطباق الطازجة لا تُستبدل ولا تُرجع. في حال وجود خلل، تواصل فوراً.',
    refundPolicyEn: 'Fresh dishes cannot be returned. Contact immediately if there is an issue.',
    specifications: { 'المكونات': 'دجاج، أرز بسمتي، بهارات كبسة، بصل، ثوم، طماطم', 'الحصص': '3-4 أشخاص', 'التخزين': 'يستهلك فور الاستلام أو خلال 6 ساعات' },
    specificationsEn: { 'Ingredients': 'Chicken, basmati rice, kabsa spices, onion, garlic, tomato', 'Servings': '3-4 people', 'Storage': 'Consume immediately or within 6 hours' },
  },

  {
    id: 10, category: 'food',
    name: 'مقلوبة الدجاج والخضار',
    nameEn: 'Chicken & Vegetable Maqluba',
    family: 'أسرة العتيبي', familyEn: 'Al-Utaibi Family',
    sellerCity: 'الرياض', sellerCityEn: 'Riyadh',
    price: 55, originalPrice: 70, rating: 4.6, reviews: 89,
    badge: 'خصم 21%', badgeEn: '21% Off', badgeColor: 'bg-red-500',
    emoji: '🥘', images: ['🥘', '🍗', '🍆', '🥕', '🍚'],
    gradient: 'from-yellow-100 to-orange-50',
    isPerishable: true, deliveryType: 'local',
    description: 'مقلوبة منزلية تقليدية بالدجاج والباذنجان والجزر والقرنبيط، مطبوخة بعناية على نار هادئة مع البهارات المنزلية. تُقلب مباشرة عند التسليم لتُقدَّم طازجة.',
    descriptionEn: 'Traditional homemade Maqluba with chicken, eggplant, carrots and cauliflower, slow-cooked with homemade spices. Flipped fresh upon delivery.',
    weight: 'وجبة لـ 4-5 أشخاص', weightEn: 'Meal for 4-5 people',
    preparationTime: 'تُطهى عند الطلب', preparationTimeEn: 'Cooked to order',
    partnerSince: 'سبتمبر 2022', partnerSinceEn: 'September 2022',
    stock: 6, certifications: ['حلال', 'طازج يومياً'], certificationsEn: ['Halal', 'Daily Fresh'],
    orderCutoff: '19:00', whatsapp: '+966501111010',
    sizes: [
      { id: 'sm', label: 'حجم صغير (3 أشخاص)', labelEn: 'Small (3 people)', priceAdj: -20 },
      { id: 'md', label: 'حجم متوسط (5 أشخاص)', labelEn: 'Medium (5 people)', priceAdj: 0  },
      { id: 'lg', label: 'حجم كبير (8 أشخاص)', labelEn: 'Large (8 people)',  priceAdj: 45 },
    ],
    colors: null, isRefundable: false,
    refundPolicy: 'الأطباق الطازجة لا تُستبدل.',
    refundPolicyEn: 'Fresh dishes cannot be returned.',
    specifications: { 'المكونات': 'دجاج، أرز، باذنجان، جزر، قرنبيط، بهارات', 'الحصص': '4-5 أشخاص', 'التخزين': 'يستهلك فور الاستلام' },
    specificationsEn: { 'Ingredients': 'Chicken, rice, eggplant, carrot, cauliflower, spices', 'Servings': '4-5 people', 'Storage': 'Consume immediately' },
  },

  // ─── جدة ───────────────────────────────────────────────────────────────────

  {
    id: 7, category: 'food',
    name: 'مكرونة بالدجاج المنزلية الطازجة',
    nameEn: 'Fresh Homemade Chicken Pasta',
    family: 'أسرة السلمي', familyEn: 'Al-Salmi Family',
    sellerCity: 'جدة', sellerCityEn: 'Jeddah',
    price: 55, originalPrice: null, rating: 4.8, reviews: 94,
    badge: 'طازج يومياً', badgeEn: 'Daily Fresh', badgeColor: 'bg-emerald-500',
    emoji: '🍝', images: ['🍝', '🍗', '🧅', '🫙', '🌿'],
    gradient: 'from-red-100 to-orange-50',
    isPerishable: true, deliveryType: 'local',
    description: 'مكرونة إيطالية منزلية مطبوخة بصدر دجاج طازج وصلصة طماطم بيتية مع توابل منزلية خاصة. كل قدر يُعدّ بحب وعناية من أسرة السلمي.',
    descriptionEn: 'Homemade Italian pasta cooked with fresh chicken breast and homemade tomato sauce with special home spices. Each pot is prepared with love by the Al-Salmi family.',
    weight: 'وجبة لـ 2-3 أشخاص', weightEn: 'Meal for 2-3 people',
    preparationTime: 'طازجة يومياً', preparationTimeEn: 'Fresh daily',
    partnerSince: 'نوفمبر 2023', partnerSinceEn: 'November 2023',
    stock: 15, certifications: ['طازج يومياً'], certificationsEn: ['Halal', 'Daily Fresh'],
    orderCutoff: '21:00', whatsapp: '+966501111007',
    sizes: [
      { id: 'sm', label: 'حجم فردي (400 جرام)',    labelEn: 'Single (400g)', priceAdj: -25 },
      { id: 'md', label: 'حجم عائلي (800 جرام)',    labelEn: 'Family (800g)', priceAdj: 0   },
      { id: 'lg', label: 'حجم الحفلات (1.5 كيلو)', labelEn: 'Party (1.5kg)', priceAdj: 55  },
    ],
    colors: null, isRefundable: false,
    refundPolicy: 'الأطباق الطازجة لا تُستبدل ولا تُرجع.',
    refundPolicyEn: 'Fresh dishes cannot be exchanged or returned.',
    specifications: { 'المكونات': 'مكرونة، دجاج طازج، طماطم، بصل، ثوم، توابل', 'الوزن': '~800 جرام', 'الحصص': '2-3 أشخاص', 'التخزين': 'يستهلك خلال 24 ساعة' },
    specificationsEn: { 'Ingredients': 'Pasta, fresh chicken, tomatoes, onion, garlic, spices', 'Weight': '~800g', 'Servings': '2-3 people', 'Storage': 'Consume within 24 hours' },
  },

  {
    id: 11, category: 'food',
    name: 'مجبوس السمك الطازج',
    nameEn: 'Fresh Fish Machboos',
    family: 'أسرة الغزالي', familyEn: 'Al-Ghazali Family',
    sellerCity: 'جدة', sellerCityEn: 'Jeddah',
    price: 75, originalPrice: null, rating: 4.7, reviews: 163,
    badge: 'اليوم فقط', badgeEn: 'Today Only', badgeColor: 'bg-blue-500',
    emoji: '🐟', images: ['🐟', '🍚', '🍋', '🌿', '🧅'],
    gradient: 'from-cyan-100 to-blue-50',
    isPerishable: true, deliveryType: 'local',
    description: 'مجبوس سمك خليجي أصيل بسمك الهامور أو الزبيدي الطازج. يُطهى مع الأرز والبصل والطماطم وبهارات السمك الخاصة. طعم البحر في منزلك.',
    descriptionEn: 'Authentic Gulf-style fish Machboos with fresh Hamour or Zubaidi. Cooked with rice, onions, tomatoes and special fish spices. The taste of the sea at home.',
    weight: 'وجبة لـ 3-4 أشخاص', weightEn: 'Meal for 3-4 people',
    preparationTime: 'يُطهى طازجاً يومياً', preparationTimeEn: 'Cooked fresh daily',
    partnerSince: 'يونيو 2022', partnerSinceEn: 'June 2022',
    stock: 7, certifications: ['طازج يومياً'], certificationsEn: ['Halal', 'Daily Fresh'],
    orderCutoff: '19:30', whatsapp: '+966501111011',
    sizes: [
      { id: 'sm', label: 'حجم فردي',     labelEn: 'Single',  priceAdj: -35 },
      { id: 'md', label: 'حجم عائلي',    labelEn: 'Family',  priceAdj: 0   },
      { id: 'lg', label: 'حجم الضيافة',  labelEn: 'Hosting', priceAdj: 65  },
    ],
    colors: null, isRefundable: false,
    refundPolicy: 'الأطباق الطازجة لا تُستبدل.',
    refundPolicyEn: 'Fresh dishes cannot be returned.',
    specifications: { 'المكونات': 'سمك طازج، أرز، بصل، طماطم، بهارات سمك', 'الحصص': '3-4 أشخاص', 'التخزين': 'يستهلك فور الاستلام' },
    specificationsEn: { 'Ingredients': 'Fresh fish, rice, onion, tomato, fish spices', 'Servings': '3-4 people', 'Storage': 'Consume immediately' },
  },

  {
    id: 12, category: 'food',
    name: 'فول مدمس بالزيت والثوم',
    nameEn: 'Foul Medames with Olive Oil & Garlic',
    family: 'أسرة الثقفي', familyEn: 'Al-Thaqafi Family',
    sellerCity: 'جدة', sellerCityEn: 'Jeddah',
    price: 30, originalPrice: null, rating: 4.5, reviews: 201,
    badge: null, badgeEn: null, badgeColor: 'bg-gray-400',
    emoji: '🫘', images: ['🫘', '🧄', '🫚', '🌿', '🍋'],
    gradient: 'from-amber-100 to-yellow-50',
    isPerishable: true, deliveryType: 'local',
    description: 'فول مدمس منزلي مطبوخ ببطء لساعات حتى يصبح ناعماً وكريمياً، يُتبَّل بزيت الزيتون البكر والليمون والثوم والكمون. وجبة الإفطار المثالية على الطريقة الحجازية.',
    descriptionEn: 'Homemade Foul Medames slow-cooked for hours until creamy and smooth, seasoned with extra virgin olive oil, lemon, garlic and cumin. The perfect Hejazi-style breakfast.',
    weight: '2 صحون كبيرة', weightEn: '2 large bowls',
    preparationTime: 'يُطهى فجراً', preparationTimeEn: 'Cooked at dawn',
    partnerSince: 'أبريل 2023', partnerSinceEn: 'April 2023',
    stock: 25, certifications: ['نباتي', 'خالٍ من الجلوتين'], certificationsEn: ['Vegan', 'Gluten-free'],
    orderCutoff: '09:00', whatsapp: '+966501111012',
    sizes: [
      { id: 'sm', label: 'صحن واحد',    labelEn: '1 bowl',  priceAdj: -12 },
      { id: 'md', label: 'صحنان كبيران', labelEn: '2 bowls', priceAdj: 0   },
      { id: 'lg', label: '4 صحون',       labelEn: '4 bowls', priceAdj: 24  },
    ],
    colors: null, isRefundable: false,
    refundPolicy: 'الأطباق الطازجة لا تُستبدل.',
    refundPolicyEn: 'Fresh dishes cannot be returned.',
    specifications: { 'المكونات': 'فول مدمس، زيت زيتون، ليمون، ثوم، كمون', 'الحصص': '2-4 أشخاص', 'التخزين': 'يستهلك فور الاستلام' },
    specificationsEn: { 'Ingredients': 'Fava beans, olive oil, lemon, garlic, cumin', 'Servings': '2-4 people', 'Storage': 'Consume immediately' },
  },

  // ─── مكة المكرمة ──────────────────────────────────────────────────────────

  {
    id: 13, category: 'food',
    name: 'كبسة اللحم على الفحم',
    nameEn: 'Charcoal Lamb Kabsa',
    family: 'أسرة القرشي', familyEn: 'Al-Qurashi Family',
    sellerCity: 'مكة المكرمة', sellerCityEn: 'Mecca',
    price: 90, originalPrice: null, rating: 4.9, reviews: 312,
    badge: 'مميز', badgeEn: 'Premium', badgeColor: 'bg-emerald-600',
    emoji: '🍖', images: ['🍖', '🍚', '🌶️', '🧅', '🌿'],
    gradient: 'from-red-100 to-rose-50',
    isPerishable: true, deliveryType: 'local',
    description: 'كبسة لحم ضأن على أصول الطبخ المكي الأصيل، تُطهى على الفحم الطبيعي لإكسابها نكهة دخانية لا تُقاوَم. مع الأرز البسمتي والبهارات المكية السرية وصلصة الدباء.',
    descriptionEn: 'Authentic Meccan-style lamb Kabsa, slow-cooked over natural charcoal for an irresistible smoky flavor. Served with basmati rice, Meccan secret spices and pumpkin sauce.',
    weight: 'وجبة لـ 4-6 أشخاص', weightEn: 'Meal for 4-6 people',
    preparationTime: 'تُطهى على الفحم', preparationTimeEn: 'Charcoal-cooked',
    partnerSince: 'يناير 2020', partnerSinceEn: 'January 2020',
    stock: 5, certifications: ['حلال', 'طازج يومياً'], certificationsEn: ['Halal', 'Daily Fresh'],
    orderCutoff: '18:00', whatsapp: '+966501111013',
    sizes: [
      { id: 'sm', label: 'وجبة صغيرة (3 أشخاص)', labelEn: 'Small (3 people)', priceAdj: -40 },
      { id: 'md', label: 'وجبة عائلية (6 أشخاص)', labelEn: 'Family (6 people)', priceAdj: 0  },
      { id: 'lg', label: 'ولائم (12 شخصاً)',        labelEn: 'Banquet (12)',      priceAdj: 80 },
    ],
    colors: null, isRefundable: false,
    refundPolicy: 'الأطباق الطازجة لا تُستبدل ولا تُرجع.',
    refundPolicyEn: 'Fresh dishes cannot be returned.',
    specifications: { 'المكونات': 'لحم ضأن، أرز بسمتي، بهارات مكية، بصل، ثوم، طماطم', 'الحصص': '4-6 أشخاص', 'التخزين': 'يستهلك فور الاستلام' },
    specificationsEn: { 'Ingredients': 'Lamb, basmati rice, Meccan spices, onion, garlic, tomato', 'Servings': '4-6 people', 'Storage': 'Consume immediately' },
  },

  {
    id: 14, category: 'food',
    name: 'هريس الدجاج الأصيل',
    nameEn: 'Authentic Chicken Harees',
    family: 'أسرة الهاشمي', familyEn: 'Al-Hashimi Family',
    sellerCity: 'مكة المكرمة', sellerCityEn: 'Mecca',
    price: 50, originalPrice: null, rating: 4.8, reviews: 176,
    badge: 'تراثي', badgeEn: 'Heritage', badgeColor: 'bg-amber-600',
    emoji: '🍲', images: ['🍲', '🌾', '🍗', '🧈', '🌿'],
    gradient: 'from-amber-100 to-orange-50',
    isPerishable: true, deliveryType: 'local',
    description: 'هريس مكي أصيل مطبوخ من القمح الكامل مع الدجاج الطازج بطريقة موروثة. يُدق حتى يصبح ناعماً كالحرير ويُقدَّم مع السمن البلدي والقرفة.',
    descriptionEn: 'Authentic Meccan Harees made from whole wheat with fresh chicken using a heritage method. Pounded until silky smooth and served with local clarified butter and cinnamon.',
    weight: 'وجبة لـ 2-3 أشخاص', weightEn: 'Meal for 2-3 people',
    preparationTime: 'يُطهى لساعات', preparationTimeEn: 'Slow-cooked for hours',
    partnerSince: 'أكتوبر 2021', partnerSinceEn: 'October 2021',
    stock: 8, certifications: ['حلال', 'تراثي'], certificationsEn: ['Halal', 'Heritage Recipe'],
    orderCutoff: '20:00', whatsapp: '+966501111014',
    sizes: [
      { id: 'sm', label: 'قدر صغير',    labelEn: 'Small pot',  priceAdj: -20 },
      { id: 'md', label: 'قدر متوسط',   labelEn: 'Medium pot', priceAdj: 0   },
      { id: 'lg', label: 'قدر كبير',    labelEn: 'Large pot',  priceAdj: 40  },
    ],
    colors: null, isRefundable: false,
    refundPolicy: 'الأطباق الطازجة لا تُستبدل.',
    refundPolicyEn: 'Fresh dishes cannot be returned.',
    specifications: { 'المكونات': 'قمح كامل، دجاج، سمن بلدي، قرفة، ملح', 'الحصص': '2-3 أشخاص', 'التخزين': 'يستهلك خلال 12 ساعة' },
    specificationsEn: { 'Ingredients': 'Whole wheat, chicken, clarified butter, cinnamon, salt', 'Servings': '2-3 people', 'Storage': 'Consume within 12 hours' },
  },

  // ─── المدينة المنورة ──────────────────────────────────────────────────────

  {
    id: 15, category: 'food',
    name: 'جريش الدجاج التقليدي',
    nameEn: 'Traditional Chicken Jareesh',
    family: 'أسرة الأنصاري', familyEn: 'Al-Ansari Family',
    sellerCity: 'المدينة المنورة', sellerCityEn: 'Medina',
    price: 48, originalPrice: null, rating: 4.7, reviews: 134,
    badge: null, badgeEn: null, badgeColor: 'bg-gray-400',
    emoji: '🫕', images: ['🫕', '🌾', '🍗', '🧅', '🧄'],
    gradient: 'from-stone-100 to-amber-50',
    isPerishable: true, deliveryType: 'local',
    description: 'جريش نجدي-حجازي أصيل مطبوخ من القمح المجروش مع الدجاج والبصل والثوم والبهارات. يُطهى بطيئاً حتى يصبح قواماً كريمياً دافئاً. وجبة موروثة من أجيال.',
    descriptionEn: 'Authentic Najdi-Hejazi Jareesh made from crushed wheat with chicken, onion, garlic and spices. Slow-cooked to a warm creamy consistency. A dish inherited through generations.',
    weight: 'وجبة لـ 3-4 أشخاص', weightEn: 'Meal for 3-4 people',
    preparationTime: 'يُطهى ببطء لساعات', preparationTimeEn: 'Slow-cooked for hours',
    partnerSince: 'مارس 2021', partnerSinceEn: 'March 2021',
    stock: 12, certifications: ['حلال', 'تراثي'], certificationsEn: ['Halal', 'Heritage'],
    orderCutoff: '20:00', whatsapp: '+966501111015',
    sizes: [
      { id: 'sm', label: 'حجم صغير',   labelEn: 'Small',  priceAdj: -20 },
      { id: 'md', label: 'حجم متوسط',  labelEn: 'Medium', priceAdj: 0   },
      { id: 'lg', label: 'حجم كبير',   labelEn: 'Large',  priceAdj: 38  },
    ],
    colors: null, isRefundable: false,
    refundPolicy: 'الأطباق الطازجة لا تُستبدل.',
    refundPolicyEn: 'Fresh dishes cannot be returned.',
    specifications: { 'المكونات': 'قمح مجروش، دجاج، بصل، ثوم، توابل', 'الحصص': '3-4 أشخاص', 'التخزين': 'يستهلك خلال 24 ساعة' },
    specificationsEn: { 'Ingredients': 'Crushed wheat, chicken, onion, garlic, spices', 'Servings': '3-4 people', 'Storage': 'Consume within 24 hours' },
  },

  {
    id: 16, category: 'food',
    name: 'مرقوق اللحم والخضار',
    nameEn: 'Lamb & Vegetable Margoog',
    family: 'أسرة الجهني', familyEn: 'Al-Juhani Family',
    sellerCity: 'المدينة المنورة', sellerCityEn: 'Medina',
    price: 70, originalPrice: null, rating: 4.8, reviews: 98,
    badge: 'منزلي أصيل', badgeEn: 'Authentic Home', badgeColor: 'bg-emerald-500',
    emoji: '🥣', images: ['🥣', '🍖', '🥕', '🍅', '🌿'],
    gradient: 'from-orange-100 to-red-50',
    isPerishable: true, deliveryType: 'local',
    description: 'مرقوق لحم ضأن منزلي بالخضار الطازجة، مطبوخ بعجينة رقيقة محلية مع الجزر والكوسا والطماطم والبطاطس وبهارات الديار. طبق دافئ ومشبع يعيد لك ذكريات مطبخ الجدة.',
    descriptionEn: 'Homemade lamb Margoog with fresh vegetables, cooked with thin local dough, carrots, zucchini, tomatoes, potatoes and home spices. A warm, hearty dish that brings back grandmother\'s kitchen memories.',
    weight: 'وجبة لـ 4-5 أشخاص', weightEn: 'Meal for 4-5 people',
    preparationTime: 'يُطهى عند الطلب', preparationTimeEn: 'Cooked to order',
    partnerSince: 'يوليو 2022', partnerSinceEn: 'July 2022',
    stock: 6, certifications: ['حلال', 'طازج'], certificationsEn: ['Halal', 'Fresh'],
    orderCutoff: '18:00', whatsapp: '+966501111016',
    sizes: [
      { id: 'sm', label: 'قدر صغير',  labelEn: 'Small pot',  priceAdj: -30 },
      { id: 'md', label: 'قدر متوسط', labelEn: 'Medium pot', priceAdj: 0   },
      { id: 'lg', label: 'قدر كبير',  labelEn: 'Large pot',  priceAdj: 55  },
    ],
    colors: null, isRefundable: false,
    refundPolicy: 'الأطباق الطازجة لا تُستبدل.',
    refundPolicyEn: 'Fresh dishes cannot be returned.',
    specifications: { 'المكونات': 'لحم ضأن، عجين رقيق، خضار طازجة، بهارات', 'الحصص': '4-5 أشخاص', 'التخزين': 'يستهلك فور الاستلام' },
    specificationsEn: { 'Ingredients': 'Lamb, thin dough, fresh vegetables, spices', 'Servings': '4-5 people', 'Storage': 'Consume immediately' },
  },

  // ─── ينبع ──────────────────────────────────────────────────────────────────

  {
    id: 17, category: 'food',
    name: 'سمك هامور مشوي بالبهارات',
    nameEn: 'Grilled Hamour Fish with Spices',
    family: 'أسرة البحري', familyEn: 'Al-Bahri Family',
    sellerCity: 'ينبع', sellerCityEn: 'Yanbu',
    price: 80, originalPrice: null, rating: 4.9, reviews: 267,
    badge: 'طازج من البحر', badgeEn: 'Sea Fresh', badgeColor: 'bg-blue-600',
    emoji: '🐠', images: ['🐠', '🍋', '🌿', '🫚', '🧄'],
    gradient: 'from-cyan-100 to-teal-50',
    isPerishable: true, deliveryType: 'local',
    description: 'هامور بحر أحمر طازج يُشوى على الفحم بعد تتبيله بخلطة البهارات الساحلية الخاصة بأسرة البحري. يُقدَّم مع الأرز والخبز ودقة المجبوس وشرائح الليمون.',
    descriptionEn: 'Fresh Red Sea Hamour grilled over charcoal after marinating with Al-Bahri family\'s special coastal spice blend. Served with rice, bread, Daqqah sauce and lemon slices.',
    weight: 'سمكة كاملة (حسب الوزن)', weightEn: 'Whole fish (by weight)',
    preparationTime: 'يُشوى طازجاً عند الطلب', preparationTimeEn: 'Grilled fresh to order',
    partnerSince: 'يناير 2021', partnerSinceEn: 'January 2021',
    stock: 10, certifications: ['طازج من البحر'], certificationsEn: ['Sea Fresh', 'Halal'],
    orderCutoff: '20:00', whatsapp: '+966501111017',
    sizes: [
      { id: 'sm', label: 'سمكة صغيرة (~500 جرام)',  labelEn: 'Small (~500g)',  priceAdj: -40 },
      { id: 'md', label: 'سمكة متوسطة (~1 كيلو)',   labelEn: 'Medium (~1kg)', priceAdj: 0   },
      { id: 'lg', label: 'سمكة كبيرة (~1.5 كيلو)',  labelEn: 'Large (~1.5kg)', priceAdj: 55 },
    ],
    colors: null, isRefundable: false,
    refundPolicy: 'الأسماك الطازجة لا تُستبدل ولا تُرجع بعد التسليم.',
    refundPolicyEn: 'Fresh fish cannot be returned after delivery.',
    specifications: { 'النوع': 'هامور بحر أحمر', 'الطريقة': 'مشوي على الفحم', 'التتبيل': 'بهارات ساحلية، ثوم، ليمون، زيت زيتون', 'يُقدَّم مع': 'أرز أبيض، خبز، دقة، ليمون' },
    specificationsEn: { 'Type': 'Red Sea Hamour', 'Method': 'Charcoal grilled', 'Marinade': 'Coastal spices, garlic, lemon, olive oil', 'Served with': 'White rice, bread, Daqqah, lemon' },
  },

  {
    id: 18, category: 'food',
    name: 'ربيان بالثوم والزبدة',
    nameEn: 'Shrimp with Garlic & Butter',
    family: 'أسرة الينبعاوي', familyEn: 'Al-Yanbuawi Family',
    sellerCity: 'ينبع', sellerCityEn: 'Yanbu',
    price: 95, originalPrice: 120, rating: 4.8, reviews: 145,
    badge: 'خصم 21%', badgeEn: '21% Off', badgeColor: 'bg-red-500',
    emoji: '🦐', images: ['🦐', '🧄', '🧈', '🌿', '🍋'],
    gradient: 'from-orange-100 to-amber-50',
    isPerishable: true, deliveryType: 'local',
    description: 'ربيان بحر أحمر طازج مطبوخ على طريقة الثوم والزبدة مع رشة الفلفل الحار والبقدونس الطازج. يُقدَّم ساخناً مع الخبز لتنظيف الصلصة.',
    descriptionEn: 'Fresh Red Sea shrimp cooked in garlic butter with a hint of chili and fresh parsley. Served hot with bread for sauce dipping.',
    weight: '500 جرام مُنظَّف', weightEn: '500g cleaned',
    preparationTime: 'يُطهى طازجاً عند الطلب', preparationTimeEn: 'Cooked fresh to order',
    partnerSince: 'مارس 2023', partnerSinceEn: 'March 2023',
    stock: 8, certifications: ['طازج من البحر'], certificationsEn: ['Sea Fresh', 'Halal'],
    orderCutoff: '20:30', whatsapp: '+966501111018',
    sizes: [
      { id: 'sm', label: '250 جرام',  labelEn: '250g', priceAdj: -45 },
      { id: 'md', label: '500 جرام',  labelEn: '500g', priceAdj: 0   },
      { id: 'lg', label: '1 كيلو',    labelEn: '1kg',  priceAdj: 80  },
    ],
    colors: null, isRefundable: false,
    refundPolicy: 'المأكولات البحرية الطازجة لا تُستبدل بعد التسليم.',
    refundPolicyEn: 'Fresh seafood cannot be returned after delivery.',
    specifications: { 'المكونات': 'ربيان طازج، زبدة، ثوم، فلفل، بقدونس، ليمون', 'الوزن': '500 جرام مُنظَّف', 'التخزين': 'يستهلك فور الاستلام' },
    specificationsEn: { 'Ingredients': 'Fresh shrimp, butter, garlic, chili, parsley, lemon', 'Weight': '500g cleaned', 'Storage': 'Consume immediately' },
  },

  // ══════════════════════════════════════════════════════════════════════════
  // SWEETS — Perishable · Local Delivery
  // ══════════════════════════════════════════════════════════════════════════

  // ─── جدة ───────────────────────────────────────────────────────────────────

  {
    id: 2, category: 'sweets',
    name: 'كيكة الليمون بالقشطة الطازجة',
    nameEn: 'Lemon Cream Cake',
    family: 'أسرة الغامدي', familyEn: 'Al-Ghamdi Family',
    sellerCity: 'جدة', sellerCityEn: 'Jeddah',
    price: 85, originalPrice: null, rating: 4.9, reviews: 203,
    badge: 'جديد', badgeEn: 'New', badgeColor: 'bg-blue-500',
    emoji: '🍋', images: ['🍋', '🎂', '🍰', '🧁', '🫙'],
    gradient: 'from-yellow-200 to-amber-100',
    isPerishable: true, deliveryType: 'local',
    description: 'كيكة ليمون طرية بطعم حامض منعش مع طبقة قشطة طازجة كريمية. تُخبز بالزبدة الطبيعية ودقيق القمح الأبيض. مثالية للمناسبات والتجمعات العائلية.',
    descriptionEn: 'Soft lemon cake with a refreshing tang and a rich fresh cream layer. Baked with natural butter and white wheat flour. Perfect for occasions and family gatherings.',
    weight: 'قالب كامل (~8 قطع)', weightEn: 'Full tray (~8 pieces)',
    preparationTime: 'تُخبز عند الطلب', preparationTimeEn: 'Baked to order',
    partnerSince: 'يوليو 2023', partnerSinceEn: 'July 2023',
    stock: 3, orderCutoff: '20:00', whatsapp: '+966501111002',
    sizes: [
      { id: 'half',   label: 'نصف قالب',  labelEn: 'Half Tray',  priceAdj: -35 },
      { id: 'full',   label: 'قالب كامل', labelEn: 'Full Tray',  priceAdj: 0   },
      { id: 'double', label: 'قالبان',    labelEn: 'Two Trays',  priceAdj: 80  },
    ],
    colors: [
      { id: 'lemon',      label: 'ليمون',    labelEn: 'Lemon',      hex: '#FDE68A' },
      { id: 'strawberry', label: 'فراولة',   labelEn: 'Strawberry', hex: '#FB7185' },
      { id: 'chocolate',  label: 'شوكولاتة', labelEn: 'Chocolate',  hex: '#78350F' },
    ],
    isRefundable: false,
    refundPolicy: 'المخبوزات الطازجة لا تُستبدل ولا تُرجع.',
    refundPolicyEn: 'Fresh baked goods cannot be exchanged or returned.',
    specifications: { 'المكونات': 'دقيق، بيض، زبدة طبيعية، سكر، ليمون، قشطة طازجة', 'الحجم': 'قالب 24×24 سم', 'الحصص': '8-10 أشخاص', 'التخزين': 'في الثلاجة، يستهلك خلال 24 ساعة' },
    specificationsEn: { 'Ingredients': 'Flour, eggs, natural butter, sugar, lemon, fresh cream', 'Size': '24×24 cm tray', 'Servings': '8-10 people', 'Storage': 'Refrigerated, consume within 24 hours' },
  },

  {
    id: 19, category: 'sweets',
    name: 'كنافة بالجبن الطازج',
    nameEn: 'Knafeh with Fresh Cheese',
    family: 'أسرة الحجازي', familyEn: 'Al-Hijazi Family',
    sellerCity: 'جدة', sellerCityEn: 'Jeddah',
    price: 65, originalPrice: null, rating: 4.8, reviews: 289,
    badge: 'الأكثر مبيعاً', badgeEn: 'Best Seller', badgeColor: 'bg-amber-500',
    emoji: '🧀', images: ['🧀', '🍯', '🌹', '🥐', '✨'],
    gradient: 'from-amber-200 to-orange-100',
    isPerishable: true, deliveryType: 'local',
    description: 'كنافة حجازية أصيلة بعجينة القطايف المقرمشة وجبن قشطة طازج وعسل قطر مصفى ورشة ماء الورد. تُقدَّم ساخنة مع المكسرات المحمصة.',
    descriptionEn: 'Authentic Hejazi Knafeh with crispy shredded pastry, fresh cream cheese, clarified syrup and rose water. Served hot with toasted nuts.',
    weight: 'صينية متوسطة (~6 قطع)', weightEn: 'Medium tray (~6 pieces)',
    preparationTime: 'تُعدّ يومياً', preparationTimeEn: 'Prepared daily',
    partnerSince: 'مايو 2022', partnerSinceEn: 'May 2022',
    stock: 10, orderCutoff: '21:00', whatsapp: '+966501111019',
    sizes: [
      { id: 'sm', label: 'حصة فردية',      labelEn: 'Single portion', priceAdj: -40 },
      { id: 'md', label: 'صينية متوسطة',   labelEn: 'Medium tray',    priceAdj: 0   },
      { id: 'lg', label: 'صينية كبيرة',    labelEn: 'Large tray',     priceAdj: 55  },
    ],
    colors: [
      { id: 'orange',    label: 'برتقالية تقليدية', labelEn: 'Classic Orange',  hex: '#EA580C' },
      { id: 'pistachio', label: 'فستق',             labelEn: 'Pistachio',       hex: '#4D7C0F' },
    ],
    isRefundable: false,
    refundPolicy: 'الحلويات الطازجة لا تُستبدل بعد التسليم.',
    refundPolicyEn: 'Fresh sweets cannot be returned after delivery.',
    specifications: { 'المكونات': 'عجينة كنافة، جبن قشطة طازج، قطر، ماء ورد، مكسرات', 'الحصص': '4-6 أشخاص', 'التخزين': 'يستهلك فور الاستلام' },
    specificationsEn: { 'Ingredients': 'Knafeh dough, fresh cream cheese, syrup, rose water, nuts', 'Servings': '4-6 people', 'Storage': 'Consume immediately' },
  },

  // ─── الرياض ────────────────────────────────────────────────────────────────

  {
    id: 20, category: 'sweets',
    name: 'لقيمات بالعسل والسمسم',
    nameEn: 'Luqaimat with Honey & Sesame',
    family: 'أسرة الرشيد', familyEn: 'Al-Rasheed Family',
    sellerCity: 'الرياض', sellerCityEn: 'Riyadh',
    price: 35, originalPrice: null, rating: 4.6, reviews: 178,
    badge: null, badgeEn: null, badgeColor: 'bg-gray-400',
    emoji: '🍩', images: ['🍩', '🍯', '🌿', '⚡', '✨'],
    gradient: 'from-amber-100 to-yellow-50',
    isPerishable: true, deliveryType: 'local',
    description: 'لقيمات ذهبية مقرمشة من الخارج وطرية من الداخل، تُقدَّم ساخنة مع العسل الطبيعي ورشة السمسم المحمص. تُعدّ لحظة الطلب لضمان الجودة المثلى.',
    descriptionEn: 'Golden Luqaimat, crispy on the outside and soft inside, served hot drizzled with natural honey and toasted sesame. Made fresh to order for best quality.',
    weight: '~30 حبة', weightEn: '~30 pieces',
    preparationTime: 'تُقلى عند الطلب', preparationTimeEn: 'Fried to order',
    partnerSince: 'سبتمبر 2023', partnerSinceEn: 'September 2023',
    stock: 50, certifications: ['نباتي'], certificationsEn: ['Vegan', 'Halal'],
    orderCutoff: '22:00', whatsapp: '+966501111020',
    sizes: [
      { id: 'sm', label: '15 حبة',  labelEn: '15 pieces', priceAdj: -16 },
      { id: 'md', label: '30 حبة',  labelEn: '30 pieces', priceAdj: 0   },
      { id: 'lg', label: '60 حبة',  labelEn: '60 pieces', priceAdj: 28  },
    ],
    colors: [
      { id: 'honey',     label: 'بالعسل',           labelEn: 'With Honey',       hex: '#C9A84C' },
      { id: 'chocolate', label: 'بالشوكولاتة',       labelEn: 'With Chocolate',   hex: '#78350F' },
      { id: 'lotus',     label: 'بكريمة اللوتس',     labelEn: 'With Lotus Cream', hex: '#D97706' },
    ],
    isRefundable: false,
    refundPolicy: 'الحلويات الطازجة لا تُستبدل.',
    refundPolicyEn: 'Fresh sweets cannot be returned.',
    specifications: { 'المكونات': 'دقيق، خميرة، زيت، عسل، سمسم', 'العدد': '~30 حبة', 'التخزين': 'يستهلك فور الاستلام' },
    specificationsEn: { 'Ingredients': 'Flour, yeast, oil, honey, sesame', 'Count': '~30 pieces', 'Storage': 'Consume immediately' },
  },

  {
    id: 21, category: 'sweets',
    name: 'بسبوسة بالقشطة والمكسرات',
    nameEn: 'Basbousa with Cream & Nuts',
    family: 'أسرة السبيعي', familyEn: 'Al-Subai Family',
    sellerCity: 'الرياض', sellerCityEn: 'Riyadh',
    price: 45, originalPrice: 55, rating: 4.7, reviews: 122,
    badge: 'خصم', badgeEn: 'Sale', badgeColor: 'bg-red-500',
    emoji: '🍰', images: ['🍰', '🥥', '🌹', '🍯', '🥜'],
    gradient: 'from-amber-100 to-orange-50',
    isPerishable: true, deliveryType: 'local',
    description: 'بسبوسة منزلية ناعمة بالسميد والجوز الهند، مروية بالقطر وماء الورد، مزيّنة بطبقة القشطة الكريمية والمكسرات المحمصة. تُخبز وتُسلَّم طازجة.',
    descriptionEn: 'Homemade semolina cake with coconut, soaked in syrup and rose water, topped with creamy Qishta and toasted nuts. Baked and delivered fresh.',
    weight: 'قالب 20×20 سم', weightEn: '20×20 cm tray',
    preparationTime: 'تُخبز عند الطلب', preparationTimeEn: 'Baked to order',
    partnerSince: 'أبريل 2022', partnerSinceEn: 'April 2022',
    stock: 15, orderCutoff: '20:00', whatsapp: '+966501111021',
    sizes: [
      { id: 'sm', label: 'نصف قالب',  labelEn: 'Half tray', priceAdj: -20 },
      { id: 'md', label: 'قالب كامل', labelEn: 'Full tray', priceAdj: 0   },
      { id: 'lg', label: 'قالبان',    labelEn: 'Two trays', priceAdj: 38  },
    ],
    colors: null, isRefundable: false,
    refundPolicy: 'الحلويات الطازجة لا تُستبدل.',
    refundPolicyEn: 'Fresh sweets cannot be returned.',
    specifications: { 'المكونات': 'سميد، جوز هند، بيض، سكر، قشطة، مكسرات', 'الحصص': '6-8 أشخاص', 'التخزين': 'في الثلاجة، يستهلك خلال 48 ساعة' },
    specificationsEn: { 'Ingredients': 'Semolina, coconut, eggs, sugar, Qishta, nuts', 'Servings': '6-8 people', 'Storage': 'Refrigerated, within 48 hours' },
  },

  // ─── مكة المكرمة ──────────────────────────────────────────────────────────

  {
    id: 22, category: 'sweets',
    name: 'بلح الشام المحشو بالقشطة',
    nameEn: 'Balah El-Sham Stuffed with Cream',
    family: 'أسرة المكي', familyEn: 'Al-Makki Family',
    sellerCity: 'مكة المكرمة', sellerCityEn: 'Mecca',
    price: 40, originalPrice: null, rating: 4.8, reviews: 156,
    badge: 'حجازي أصيل', badgeEn: 'Authentic Hejazi', badgeColor: 'bg-emerald-600',
    emoji: '🥐', images: ['🥐', '🍮', '🌹', '🍯', '✨'],
    gradient: 'from-amber-200 to-yellow-100',
    isPerishable: true, deliveryType: 'local',
    description: 'بلح شام مقرمش يُقلى بزيت نقي ثم يُحشى بكريمة القشطة الطازجة ويُرش بالقطر وماء الورد والفستق المطحون. من أشهر حلويات الرمضانيات الحجازية.',
    descriptionEn: 'Crispy Balah El-Sham fried in pure oil, stuffed with fresh cream and drizzled with syrup, rose water and ground pistachio. One of the most famous Ramadan Hejazi sweets.',
    weight: '~20 قطعة', weightEn: '~20 pieces',
    preparationTime: 'تُعدّ يومياً', preparationTimeEn: 'Prepared daily',
    partnerSince: 'يناير 2023', partnerSinceEn: 'January 2023',
    stock: 20, orderCutoff: '21:00', whatsapp: '+966501111022',
    sizes: [
      { id: 'sm', label: '10 قطع',  labelEn: '10 pieces', priceAdj: -18 },
      { id: 'md', label: '20 قطعة', labelEn: '20 pieces', priceAdj: 0   },
      { id: 'lg', label: '40 قطعة', labelEn: '40 pieces', priceAdj: 35  },
    ],
    colors: null, isRefundable: false,
    refundPolicy: 'الحلويات الطازجة لا تُستبدل.',
    refundPolicyEn: 'Fresh sweets cannot be returned.',
    specifications: { 'المكونات': 'دقيق، بيض، قشطة، سكر، ماء ورد، فستق', 'العدد': '~20 قطعة', 'التخزين': 'يستهلك فور الاستلام' },
    specificationsEn: { 'Ingredients': 'Flour, eggs, cream, sugar, rose water, pistachio', 'Count': '~20 pieces', 'Storage': 'Consume immediately' },
  },

  // ─── المدينة المنورة ──────────────────────────────────────────────────────

  {
    id: 23, category: 'sweets',
    name: 'محلابية بماء الورد والفستق',
    nameEn: 'Muhallabia with Rose Water & Pistachio',
    family: 'أسرة الحسيني', familyEn: 'Al-Husseini Family',
    sellerCity: 'المدينة المنورة', sellerCityEn: 'Medina',
    price: 30, originalPrice: null, rating: 4.7, reviews: 114,
    badge: null, badgeEn: null, badgeColor: 'bg-gray-400',
    emoji: '🍮', images: ['🍮', '🌹', '🥜', '🍯', '🌸'],
    gradient: 'from-pink-100 to-rose-50',
    isPerishable: true, deliveryType: 'local',
    description: 'محلابية مدنية راقية مصنوعة من الحليب الطازج بالسكر وماء الورد ومستكة طبيعية، تُزيَّن بالفستق الحلبي المطحون وبتلات الورد. حلوى هادئة الطعم وعالية الأناقة.',
    descriptionEn: 'Elegant Medinese Muhallabia made from fresh milk with sugar, rose water and natural mastic, decorated with ground pistachio and rose petals. A subtly flavored and elegantly presented dessert.',
    weight: '4 أكواب', weightEn: '4 cups',
    preparationTime: 'تُعدّ وتُبرَّد يومياً', preparationTimeEn: 'Prepared and chilled daily',
    partnerSince: 'نوفمبر 2022', partnerSinceEn: 'November 2022',
    stock: 30, orderCutoff: '21:00', whatsapp: '+966501111023',
    sizes: [
      { id: 'sm', label: 'كوبان',    labelEn: '2 cups', priceAdj: -13 },
      { id: 'md', label: '4 أكواب',  labelEn: '4 cups', priceAdj: 0   },
      { id: 'lg', label: '8 أكواب',  labelEn: '8 cups', priceAdj: 24  },
    ],
    colors: null, isRefundable: false,
    refundPolicy: 'الحلويات الطازجة لا تُستبدل.',
    refundPolicyEn: 'Fresh sweets cannot be returned.',
    specifications: { 'المكونات': 'حليب طازج، سكر، نشا، ماء ورد، مستكة، فستق', 'الحصص': '4 أشخاص', 'التخزين': 'في الثلاجة، يستهلك خلال 24 ساعة' },
    specificationsEn: { 'Ingredients': 'Fresh milk, sugar, starch, rose water, mastic, pistachio', 'Servings': '4 people', 'Storage': 'Refrigerated, within 24 hours' },
  },

  // ─── ينبع ──────────────────────────────────────────────────────────────────

  {
    id: 24, category: 'sweets',
    name: 'قطايف بالقشطة والمكسرات',
    nameEn: 'Qatayef with Cream & Nuts',
    family: 'أسرة الساحلي', familyEn: 'Al-Sahili Family',
    sellerCity: 'ينبع', sellerCityEn: 'Yanbu',
    price: 38, originalPrice: null, rating: 4.6, reviews: 91,
    badge: null, badgeEn: null, badgeColor: 'bg-gray-400',
    emoji: '🥟', images: ['🥟', '🍮', '🥜', '🍯', '🌹'],
    gradient: 'from-amber-100 to-yellow-50',
    isPerishable: true, deliveryType: 'local',
    description: 'قطايف منزلية ناعمة محشوة بالقشطة الطازجة أو الجبن الحلومي أو المكسرات المحمصة بالسكر والقرفة، تُقلى ثم تُغمس بالقطر والعسل. اختر حشوتك المفضلة.',
    descriptionEn: 'Soft homemade Qatayef stuffed with fresh cream, Halloumi cheese, or nuts with sugar and cinnamon, fried and dipped in syrup and honey. Choose your favorite filling.',
    weight: '~15 قطعة', weightEn: '~15 pieces',
    preparationTime: 'تُعدّ يومياً', preparationTimeEn: 'Prepared daily',
    partnerSince: 'أغسطس 2023', partnerSinceEn: 'August 2023',
    stock: 25, orderCutoff: '21:30', whatsapp: '+966501111024',
    sizes: [
      { id: 'sm', label: '8 قطع',   labelEn: '8 pieces',  priceAdj: -18 },
      { id: 'md', label: '15 قطعة', labelEn: '15 pieces', priceAdj: 0   },
      { id: 'lg', label: '30 قطعة', labelEn: '30 pieces', priceAdj: 32  },
    ],
    colors: [
      { id: 'cream', label: 'قشطة',    labelEn: 'Cream',      hex: '#FEF9C3' },
      { id: 'nuts',  label: 'مكسرات',  labelEn: 'Nuts',       hex: '#C9A84C' },
      { id: 'cheese',label: 'جبن',     labelEn: 'Cheese',     hex: '#FFFBEB' },
    ],
    isRefundable: false,
    refundPolicy: 'الحلويات الطازجة لا تُستبدل.',
    refundPolicyEn: 'Fresh sweets cannot be returned.',
    specifications: { 'المكونات': 'دقيق، بيض، خميرة، قشطة/مكسرات/جبن، قطر', 'العدد': '~15 قطعة', 'التخزين': 'يستهلك فور الاستلام' },
    specificationsEn: { 'Ingredients': 'Flour, eggs, yeast, cream/nuts/cheese, syrup', 'Count': '~15 pieces', 'Storage': 'Consume immediately' },
  },

  // ══════════════════════════════════════════════════════════════════════════
  // FROZEN — Non-Perishable · Ships Nationwide
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 25, category: 'frozen',
    name: 'سمبوسة الجبن المجمدة',
    nameEn: 'Frozen Cheese Samboosa',
    family: 'أسرة الزيد', familyEn: 'Al-Zaid Family',
    sellerCity: 'الرياض', sellerCityEn: 'Riyadh',
    price: 45, originalPrice: null, rating: 4.6, reviews: 187,
    badge: null, badgeEn: null, badgeColor: 'bg-gray-400',
    emoji: '🥟', images: ['🥟', '🧀', '🌿', '❄️', '📦'],
    gradient: 'from-blue-100 to-cyan-50',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'سمبوسة منزلية مجمدة جاهزة للقلي أو الفرن. عجينة رقيقة مقرمشة محشوة بالجبن الأبيض والبقدونس والنعنع. تُحفَظ في الفريزر وتُقلى مباشرة دون تذويب.',
    descriptionEn: 'Homemade frozen Samboosa ready to fry or bake. Thin crispy dough stuffed with white cheese, parsley and mint. Kept frozen and fried directly without thawing.',
    weight: '~30 قطعة (600 جرام)', weightEn: '~30 pieces (600g)',
    preparationTime: 'جاهزة للقلي مباشرة', preparationTimeEn: 'Ready to fry directly',
    partnerSince: 'أغسطس 2022', partnerSinceEn: 'August 2022',
    stock: 60, certifications: ['نباتي'], certificationsEn: ['Vegetarian', 'Halal'],
    orderCutoff: null, whatsapp: '+966501111025',
    sizes: [
      { id: 'sm', label: '15 قطعة',  labelEn: '15 pieces', priceAdj: -20 },
      { id: 'md', label: '30 قطعة',  labelEn: '30 pieces', priceAdj: 0   },
      { id: 'lg', label: '60 قطعة',  labelEn: '60 pieces', priceAdj: 38  },
    ],
    colors: [
      { id: 'cheese',   label: 'جبن',         labelEn: 'Cheese',       hex: '#FFFBEB' },
      { id: 'meat',     label: 'لحم',          labelEn: 'Meat',         hex: '#7B3F00' },
      { id: 'spinach',  label: 'سبانخ وجبن',  labelEn: 'Spinach & Cheese', hex: '#166534' },
    ],
    isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتجات المجمدة غير المفتوحة خلال 7 أيام.',
    refundPolicyEn: 'Unopened frozen products can be returned within 7 days.',
    specifications: { 'المكونات': 'عجينة، جبن أبيض، بقدونس، نعنع', 'العدد': '~30 قطعة', 'الصلاحية (مجمد)': '3 أشهر', 'طريقة الطهي': 'قلي أو فرن مباشرة من الفريزر' },
    specificationsEn: { 'Ingredients': 'Dough, white cheese, parsley, mint', 'Count': '~30 pieces', 'Frozen shelf life': '3 months', 'Cooking': 'Fry or bake directly from frozen' },
  },

  {
    id: 26, category: 'frozen',
    name: 'ملفوف محشي مجمد',
    nameEn: 'Frozen Stuffed Cabbage Rolls',
    family: 'أسرة البقمي', familyEn: 'Al-Baqami Family',
    sellerCity: 'جدة', sellerCityEn: 'Jeddah',
    price: 55, originalPrice: null, rating: 4.5, reviews: 143,
    badge: null, badgeEn: null, badgeColor: 'bg-gray-400',
    emoji: '🥬', images: ['🥬', '🍚', '🧄', '❄️', '📦'],
    gradient: 'from-green-100 to-emerald-50',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'ملفوف محشي منزلي مجمد بالأرز واللحم المفروم والبصل والبهارات المنزلية. تُغلى مباشرة من الفريزر في صلصة الطماطم. وجبة منزلية دافئة جاهزة في 30 دقيقة.',
    descriptionEn: 'Homemade frozen stuffed cabbage rolls with rice, minced meat, onion and homemade spices. Boiled directly from frozen in tomato sauce. A warm home meal ready in 30 minutes.',
    weight: '~25 رول (700 جرام)', weightEn: '~25 rolls (700g)',
    preparationTime: 'تُطهى من الفريزر مباشرة', preparationTimeEn: 'Cooked directly from frozen',
    partnerSince: 'مارس 2023', partnerSinceEn: 'March 2023',
    stock: 40, certifications: ['حلال'], certificationsEn: ['Halal'],
    orderCutoff: null, whatsapp: '+966501111026',
    sizes: [
      { id: 'sm', label: '12 رول',  labelEn: '12 rolls', priceAdj: -25 },
      { id: 'md', label: '25 رول',  labelEn: '25 rolls', priceAdj: 0   },
      { id: 'lg', label: '50 رول',  labelEn: '50 rolls', priceAdj: 48  },
    ],
    colors: null, isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتجات المجمدة غير المفتوحة خلال 7 أيام.',
    refundPolicyEn: 'Unopened frozen products can be returned within 7 days.',
    specifications: { 'المكونات': 'ملفوف، أرز، لحم مفروم، بصل، بهارات', 'العدد': '~25 رول', 'الصلاحية (مجمد)': '3 أشهر', 'طريقة الطهي': 'غلي في صلصة الطماطم 30 دقيقة' },
    specificationsEn: { 'Ingredients': 'Cabbage, rice, minced meat, onion, spices', 'Count': '~25 rolls', 'Frozen shelf life': '3 months', 'Cooking': 'Boil in tomato sauce 30 minutes' },
  },

  {
    id: 27, category: 'frozen',
    name: 'لفائف الدجاج بالجبن المجمدة',
    nameEn: 'Frozen Chicken & Cheese Rolls',
    family: 'أسرة المدني', familyEn: 'Al-Madani Family',
    sellerCity: 'المدينة المنورة', sellerCityEn: 'Medina',
    price: 50, originalPrice: null, rating: 4.7, reviews: 209,
    badge: 'الأكثر طلباً', badgeEn: 'Most Ordered', badgeColor: 'bg-emerald-500',
    emoji: '🌯', images: ['🌯', '🍗', '🧀', '❄️', '📦'],
    gradient: 'from-amber-100 to-orange-50',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'لفائف منزلية مجمدة بحشوة الدجاج المتبل بالبهارات والجبن الذائب والفليفلة الملونة. تُخبز في الفرن أو تُقلى حتى تتحول إلى ذهبية مقرمشة.',
    descriptionEn: 'Homemade frozen rolls stuffed with spiced chicken, melted cheese and colorful peppers. Baked or fried until golden and crispy.',
    weight: '~20 لفيفة (600 جرام)', weightEn: '~20 rolls (600g)',
    preparationTime: 'فرن 20 دقيقة من الفريزر', preparationTimeEn: 'Oven 20 mins from frozen',
    partnerSince: 'يونيو 2023', partnerSinceEn: 'June 2023',
    stock: 55, certifications: ['حلال'], certificationsEn: ['Halal'],
    orderCutoff: null, whatsapp: '+966501111027',
    sizes: [
      { id: 'sm', label: '10 لفائف', labelEn: '10 rolls', priceAdj: -22 },
      { id: 'md', label: '20 لفيفة', labelEn: '20 rolls', priceAdj: 0   },
      { id: 'lg', label: '40 لفيفة', labelEn: '40 rolls', priceAdj: 42  },
    ],
    colors: null, isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتجات المجمدة غير المفتوحة خلال 7 أيام.',
    refundPolicyEn: 'Unopened frozen products can be returned within 7 days.',
    specifications: { 'المكونات': 'دجاج مفروم، جبن، فليفلة، بهارات، عجينة', 'العدد': '~20 لفيفة', 'الصلاحية (مجمد)': '3 أشهر', 'طريقة الطهي': 'فرن 180° لمدة 20 دقيقة' },
    specificationsEn: { 'Ingredients': 'Minced chicken, cheese, peppers, spices, dough', 'Count': '~20 rolls', 'Frozen shelf life': '3 months', 'Cooking': 'Oven 180° for 20 minutes' },
  },

  {
    id: 28, category: 'frozen',
    name: 'كباب مشكل مجمد',
    nameEn: 'Frozen Mixed Kebab',
    family: 'أسرة الشريف', familyEn: 'Al-Sharif Family',
    sellerCity: 'مكة المكرمة', sellerCityEn: 'Mecca',
    price: 70, originalPrice: null, rating: 4.8, reviews: 162,
    badge: null, badgeEn: null, badgeColor: 'bg-gray-400',
    emoji: '🍢', images: ['🍢', '🥩', '🧅', '❄️', '🌿'],
    gradient: 'from-red-100 to-orange-50',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'كباب مجمد مصنوع من لحم ضأن وبقري طازج مفروم بالبصل والبقدونس والبهارات الشامية. جاهز للشواء على الفحم أو المقلاة مباشرة من الفريزر.',
    descriptionEn: 'Frozen kebab made from fresh minced lamb and beef with onion, parsley and Levantine spices. Ready for charcoal or pan grilling directly from frozen.',
    weight: '~16 قطعة (800 جرام)', weightEn: '~16 pieces (800g)',
    preparationTime: 'شواء مباشر من الفريزر', preparationTimeEn: 'Grill directly from frozen',
    partnerSince: 'يناير 2022', partnerSinceEn: 'January 2022',
    stock: 35, certifications: ['حلال'], certificationsEn: ['Halal'],
    orderCutoff: null, whatsapp: '+966501111028',
    sizes: [
      { id: 'sm', label: '8 قطع',   labelEn: '8 pieces',  priceAdj: -33 },
      { id: 'md', label: '16 قطعة', labelEn: '16 pieces', priceAdj: 0   },
      { id: 'lg', label: '32 قطعة', labelEn: '32 pieces', priceAdj: 60  },
    ],
    colors: null, isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتجات المجمدة غير المفتوحة خلال 7 أيام.',
    refundPolicyEn: 'Unopened frozen products can be returned within 7 days.',
    specifications: { 'المكونات': 'لحم ضأن وبقري، بصل، بقدونس، بهارات', 'العدد': '~16 قطعة', 'الصلاحية (مجمد)': '4 أشهر', 'طريقة الطهي': 'شواء أو قلي مباشرة من الفريزر' },
    specificationsEn: { 'Ingredients': 'Lamb & beef, onion, parsley, spices', 'Count': '~16 pieces', 'Frozen shelf life': '4 months', 'Cooking': 'Grill or fry directly from frozen' },
  },

  // ══════════════════════════════════════════════════════════════════════════
  // SPICES — Non-Perishable · Ships Nationwide
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 3, category: 'spices',
    name: 'بهارات القصيم الأصيلة',
    nameEn: 'Al-Qassim Authentic Spice Blend',
    family: 'أسرة العنزي', familyEn: 'Al-Anazi Family',
    sellerCity: 'الرياض', sellerCityEn: 'Riyadh',
    price: 30, originalPrice: 38, rating: 4.7, reviews: 89,
    badge: 'خصم 21%', badgeEn: '21% Off', badgeColor: 'bg-red-500',
    emoji: '🌶️', images: ['🌶️', '🫙', '🌿', '🧄', '🫚'],
    gradient: 'from-orange-200 to-red-100',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'خلطة بهارات أصيلة مكوّنة من أكثر من 12 نوعاً من التوابل المختارة يدوياً. تُضاف للكبسة والمندي وسائر المطبخ النجدي لإضفاء نكهة أصيلة لا تُنسى.',
    descriptionEn: 'Authentic spice blend made of more than 12 hand-selected spice varieties. Added to Kabsa, Mandi, and other Najdi dishes for an unforgettable authentic flavor.',
    weight: '250 جرام', weightEn: '250g',
    preparationTime: 'تُحضّر وتُطحن عند الطلب', preparationTimeEn: 'Prepared and ground to order',
    partnerSince: 'أبريل 2021', partnerSinceEn: 'April 2021',
    stock: 45, certifications: ['طبيعي', 'خالٍ من المنكهات الصناعية'],
    certificationsEn: ['Halal', 'Natural', 'No Artificial Flavors'],
    orderCutoff: null, whatsapp: '+966501111003',
    sizes: [
      { id: 'sm', label: '100 جرام', labelEn: '100g', priceAdj: -12 },
      { id: 'md', label: '250 جرام', labelEn: '250g', priceAdj: 0   },
      { id: 'lg', label: '500 جرام', labelEn: '500g', priceAdj: 28  },
    ],
    colors: null, isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتج خلال 7 أيام إذا كان مغلقاً.',
    refundPolicyEn: 'Product can be returned within 7 days if sealed.',
    specifications: { 'المكونات': 'خلطة من 12+ نوع من التوابل المختارة', 'الوزن': '250 جرام', 'الصلاحية': '12 شهراً', 'مستوى الحرارة': 'متوسط' },
    specificationsEn: { 'Ingredients': '12+ types of hand-selected spices', 'Weight': '250g', 'Shelf Life': '12 months', 'Heat Level': 'Medium' },
  },

  {
    id: 29, category: 'spices',
    name: 'خلطة بهارات الشاورما البيتية',
    nameEn: 'Homemade Shawarma Spice Blend',
    family: 'أسرة الصاعدي', familyEn: 'Al-Saedi Family',
    sellerCity: 'جدة', sellerCityEn: 'Jeddah',
    price: 25, originalPrice: null, rating: 4.8, reviews: 312,
    badge: 'الأكثر مبيعاً', badgeEn: 'Best Seller', badgeColor: 'bg-amber-500',
    emoji: '🫙', images: ['🫙', '🌶️', '🧄', '🌿', '🫚'],
    gradient: 'from-amber-100 to-orange-50',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'خلطة بهارات الشاورما المنزلية السرية من أسرة الصاعدي. مزيج متوازن من الكمون والكزبرة والكركم والفلفل والهيل والقرفة. تُعطي الشاورما نكهتها الأصيلة المميزة.',
    descriptionEn: 'Secret homemade Shawarma spice blend from the Al-Saedi family. A balanced mix of cumin, coriander, turmeric, pepper, cardamom and cinnamon. Gives Shawarma its distinctive authentic flavor.',
    weight: '150 جرام', weightEn: '150g',
    preparationTime: 'تُطحن طازجة عند الطلب', preparationTimeEn: 'Ground fresh to order',
    partnerSince: 'فبراير 2022', partnerSinceEn: 'February 2022',
    stock: 80, certifications: ['طبيعي', 'خالٍ من الإضافات'], certificationsEn: ['Halal', 'Natural', 'No Additives'],
    orderCutoff: null, whatsapp: '+966501111029',
    sizes: [
      { id: 'sm', label: '75 جرام',  labelEn: '75g',  priceAdj: -10 },
      { id: 'md', label: '150 جرام', labelEn: '150g', priceAdj: 0   },
      { id: 'lg', label: '300 جرام', labelEn: '300g', priceAdj: 20  },
    ],
    colors: null, isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتج خلال 7 أيام إذا كان مغلقاً.',
    refundPolicyEn: 'Product can be returned within 7 days if sealed.',
    specifications: { 'المكونات': 'كمون، كزبرة، كركم، فلفل، هيل، قرفة', 'الوزن': '150 جرام', 'الصلاحية': '12 شهراً', 'مناسب لـ': 'شاورما دجاج ولحم' },
    specificationsEn: { 'Ingredients': 'Cumin, coriander, turmeric, pepper, cardamom, cinnamon', 'Weight': '150g', 'Shelf Life': '12 months', 'Suitable for': 'Chicken and meat Shawarma' },
  },

  {
    id: 30, category: 'spices',
    name: 'بهارات السمك والمأكولات البحرية',
    nameEn: 'Fish & Seafood Spice Blend',
    family: 'أسرة البحري', familyEn: 'Al-Bahri Family',
    sellerCity: 'ينبع', sellerCityEn: 'Yanbu',
    price: 28, originalPrice: null, rating: 4.6, reviews: 134,
    badge: null, badgeEn: null, badgeColor: 'bg-gray-400',
    emoji: '🐟', images: ['🐟', '🫙', '🌿', '🍋', '🌶️'],
    gradient: 'from-teal-100 to-cyan-50',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'خلطة بهارات السمك من الساحل الحجازي، تحتوي على الكمون والكزبرة والشمر وبهارات البحر المختارة يدوياً. تُستخدم للتتبيل قبل الشواء أو للطبخ مع المجبوس.',
    descriptionEn: 'Fish spice blend from the Hejazi coast, containing cumin, coriander, fennel and hand-selected sea spices. Used for marinating before grilling or cooking with Machboos.',
    weight: '200 جرام', weightEn: '200g',
    preparationTime: 'تُطحن وتُعبَّأ عند الطلب', preparationTimeEn: 'Ground and packed to order',
    partnerSince: 'سبتمبر 2022', partnerSinceEn: 'September 2022',
    stock: 55, certifications: ['طبيعي'], certificationsEn: ['Halal', 'Natural'],
    orderCutoff: null, whatsapp: '+966501111030',
    sizes: [
      { id: 'sm', label: '100 جرام', labelEn: '100g', priceAdj: -12 },
      { id: 'md', label: '200 جرام', labelEn: '200g', priceAdj: 0   },
      { id: 'lg', label: '400 جرام', labelEn: '400g', priceAdj: 22  },
    ],
    colors: null, isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتج خلال 7 أيام إذا كان مغلقاً.',
    refundPolicyEn: 'Product can be returned within 7 days if sealed.',
    specifications: { 'المكونات': 'كمون، كزبرة، شمر، ثوم مجفف، فلفل أحمر', 'الوزن': '200 جرام', 'الصلاحية': '12 شهراً', 'مناسب لـ': 'السمك، الربيان، المأكولات البحرية' },
    specificationsEn: { 'Ingredients': 'Cumin, coriander, fennel, dried garlic, red pepper', 'Weight': '200g', 'Shelf Life': '12 months', 'Suitable for': 'Fish, shrimp, seafood' },
  },

  {
    id: 31, category: 'spices',
    name: 'خلطة بهارات المندي والمظبي',
    nameEn: 'Mandi & Madhbi Spice Blend',
    family: 'أسرة القرشي', familyEn: 'Al-Qurashi Family',
    sellerCity: 'مكة المكرمة', sellerCityEn: 'Mecca',
    price: 35, originalPrice: null, rating: 4.9, reviews: 278,
    badge: 'مميز', badgeEn: 'Premium', badgeColor: 'bg-emerald-600',
    emoji: '🌿', images: ['🌿', '🫙', '🌶️', '🧄', '🌾'],
    gradient: 'from-green-100 to-emerald-50',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'خلطة بهارات المندي والمظبي الأصيلة، وصفة مكية موروثة تجمع أكثر من 15 نوعاً من التوابل المختارة من أجود المصادر. تُعطي اللحم والدجاج نكهة لا تُنسى وعمقاً استثنائياً.',
    descriptionEn: 'Authentic Mandi and Madhbi spice blend, an inherited Meccan recipe combining over 15 types of spices selected from the finest sources. Gives meat and chicken an unforgettable depth of flavor.',
    weight: '200 جرام', weightEn: '200g',
    preparationTime: 'تُحضّر وتُطحن عند الطلب', preparationTimeEn: 'Prepared and ground to order',
    partnerSince: 'مارس 2020', partnerSinceEn: 'March 2020',
    stock: 40, certifications: ['طبيعي', 'بدون إضافات'], certificationsEn: ['Halal', 'Natural', 'No Additives'],
    orderCutoff: null, whatsapp: '+966501111031',
    sizes: [
      { id: 'sm', label: '100 جرام', labelEn: '100g', priceAdj: -15 },
      { id: 'md', label: '200 جرام', labelEn: '200g', priceAdj: 0   },
      { id: 'lg', label: '500 جرام', labelEn: '500g', priceAdj: 45  },
    ],
    colors: null, isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتج خلال 7 أيام إذا كان مغلقاً.',
    refundPolicyEn: 'Product can be returned within 7 days if sealed.',
    specifications: { 'المكونات': 'خلطة من 15+ نوع من التوابل المختارة', 'الوزن': '200 جرام', 'الصلاحية': '18 شهراً', 'مناسب لـ': 'مندي، مظبي، كبسة' },
    specificationsEn: { 'Ingredients': '15+ types of hand-selected spices', 'Weight': '200g', 'Shelf Life': '18 months', 'Suitable for': 'Mandi, Madhbi, Kabsa' },
  },

  // ══════════════════════════════════════════════════════════════════════════
  // HONEY — Non-Perishable · Ships Nationwide
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 4, category: 'honey',
    name: 'عسل السدر الجبلي الطبيعي',
    nameEn: 'Natural Mountain Sidr Honey',
    family: 'أسرة القحطاني', familyEn: 'Al-Qahtani Family',
    sellerCity: 'المدينة المنورة', sellerCityEn: 'Medina',
    price: 180, originalPrice: null, rating: 5.0, reviews: 341,
    badge: 'مميز', badgeEn: 'Premium', badgeColor: 'bg-emerald-600',
    emoji: '🍯', images: ['🍯', '🐝', '🌸', '🌳', '🫙'],
    gradient: 'from-amber-200 to-yellow-100',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'عسل سدر جبلي نقي 100% من مناحل أسرة القحطاني. يُجمع يدوياً مرة واحدة في السنة. غني بالمضادات الحيوية الطبيعية ومفيد جداً للصحة.',
    descriptionEn: '100% pure mountain sidr honey from Al-Qahtani family apiaries. Hand-harvested once a year. Rich in natural antibiotics and highly beneficial for health.',
    weight: '500 جرام', weightEn: '500g',
    preparationTime: 'طبيعي · معالج بدون حرارة', preparationTimeEn: 'Natural · cold-processed',
    partnerSince: 'ديسمبر 2020', partnerSinceEn: 'December 2020',
    stock: 12, certifications: ['عضوي', 'غير معالج بالحرارة', 'خالٍ من المواد الحافظة'],
    certificationsEn: ['Halal', 'Organic', 'Raw (Unheated)', 'Preservative-free'],
    orderCutoff: null, whatsapp: '+966501111004',
    sizes: [
      { id: 'sm', label: '250 جرام',   labelEn: '250g',       priceAdj: -80  },
      { id: 'md', label: '500 جرام',   labelEn: '500g',       priceAdj: 0    },
      { id: 'lg', label: 'كيلو كامل', labelEn: '1kg full',   priceAdj: 150  },
    ],
    colors: null, isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتج خلال 14 يوماً إذا كان مغلقاً.',
    refundPolicyEn: 'Product can be returned within 14 days if sealed.',
    specifications: { 'النوع': 'سدر جبلي طبيعي 100%', 'الوزن': '500 جرام', 'الصلاحية': 'سنتان', 'طريقة المعالجة': 'عسل خام بدون تسخين' },
    specificationsEn: { 'Type': '100% natural mountain sidr', 'Weight': '500g', 'Shelf Life': '2 years', 'Processing': 'Raw honey, no heating' },
  },

  {
    id: 32, category: 'honey',
    name: 'عسل الطلح الأبيض الجبلي',
    nameEn: 'Mountain White Talh Honey',
    family: 'أسرة الجهني', familyEn: 'Al-Juhani Family',
    sellerCity: 'ينبع', sellerCityEn: 'Yanbu',
    price: 140, originalPrice: null, rating: 4.8, reviews: 197,
    badge: null, badgeEn: null, badgeColor: 'bg-gray-400',
    emoji: '🌸', images: ['🌸', '🍯', '🐝', '🌳', '🫙'],
    gradient: 'from-yellow-100 to-amber-50',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'عسل الطلح الأبيض الجبلي من مناحل أسرة الجهني في جبال الحجاز. نكهته معتدلة وقوامه خفيف نسبياً، غني بمضادات الأكسدة الطبيعية. مناسب للاستهلاك اليومي.',
    descriptionEn: 'Mountain White Talh honey from Al-Juhani family apiaries in the Hejaz mountains. Mild flavor and relatively light consistency, rich in natural antioxidants. Suitable for daily consumption.',
    weight: '500 جرام', weightEn: '500g',
    preparationTime: 'طبيعي · بدون معالجة حرارية', preparationTimeEn: 'Natural · unheated',
    partnerSince: 'أبريل 2021', partnerSinceEn: 'April 2021',
    stock: 18, certifications: ['عضوي', 'طبيعي'], certificationsEn: ['Halal', 'Organic', 'Natural'],
    orderCutoff: null, whatsapp: '+966501111032',
    sizes: [
      { id: 'sm', label: '250 جرام', labelEn: '250g',   priceAdj: -60 },
      { id: 'md', label: '500 جرام', labelEn: '500g',   priceAdj: 0   },
      { id: 'lg', label: '1 كيلو',   labelEn: '1kg',    priceAdj: 120 },
    ],
    colors: null, isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتج خلال 14 يوماً إذا كان مغلقاً.',
    refundPolicyEn: 'Product can be returned within 14 days if sealed.',
    specifications: { 'النوع': 'طلح أبيض جبلي', 'الوزن': '500 جرام', 'الصلاحية': '2 سنة', 'اللون': 'أبيض شفاف' },
    specificationsEn: { 'Type': 'Mountain White Talh', 'Weight': '500g', 'Shelf Life': '2 years', 'Color': 'Clear white' },
  },

  {
    id: 33, category: 'honey',
    name: 'عسل السمر من مناحل الحجاز',
    nameEn: 'Samur Honey from Hejaz Apiaries',
    family: 'أسرة الهاشمي', familyEn: 'Al-Hashimi Family',
    sellerCity: 'مكة المكرمة', sellerCityEn: 'Mecca',
    price: 120, originalPrice: 150, rating: 4.7, reviews: 143,
    badge: 'خصم 20%', badgeEn: '20% Off', badgeColor: 'bg-red-500',
    emoji: '🐝', images: ['🐝', '🍯', '🌳', '🫙', '🌿'],
    gradient: 'from-amber-100 to-yellow-50',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'عسل السمر الحجازي الأصيل من مناحل أسرة الهاشمي في البوادي المحيطة بمكة المكرمة. نكهة دافئة عميقة مع لون بني ذهبي. يُعدّ من أجود أنواع العسل في الجزيرة العربية.',
    descriptionEn: 'Authentic Hejazi Samur honey from Al-Hashimi family apiaries in the wilderness around Mecca. Deep warm flavor with a golden brown color. Considered one of the finest honey types in the Arabian Peninsula.',
    weight: '500 جرام', weightEn: '500g',
    preparationTime: 'طبيعي · بدون معالجة', preparationTimeEn: 'Natural · unprocessed',
    partnerSince: 'فبراير 2022', partnerSinceEn: 'February 2022',
    stock: 20, certifications: ['طبيعي', 'خام'], certificationsEn: ['Halal', 'Natural', 'Raw'],
    orderCutoff: null, whatsapp: '+966501111033',
    sizes: [
      { id: 'sm', label: '250 جرام', labelEn: '250g', priceAdj: -50 },
      { id: 'md', label: '500 جرام', labelEn: '500g', priceAdj: 0   },
      { id: 'lg', label: '1 كيلو',   labelEn: '1kg',  priceAdj: 100 },
    ],
    colors: null, isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتج خلال 14 يوماً إذا كان مغلقاً.',
    refundPolicyEn: 'Product can be returned within 14 days if sealed.',
    specifications: { 'النوع': 'سمر حجازي', 'الوزن': '500 جرام', 'الصلاحية': '2 سنة', 'اللون': 'بني ذهبي' },
    specificationsEn: { 'Type': 'Hejazi Samur', 'Weight': '500g', 'Shelf Life': '2 years', 'Color': 'Golden brown' },
  },

  // ══════════════════════════════════════════════════════════════════════════
  // CRAFTS — Non-Perishable · Ships Nationwide
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 34, category: 'crafts',
    name: 'سدو يدوي تقليدي (مسند)',
    nameEn: 'Traditional Handwoven Sadu (Cushion)',
    family: 'أسرة المطيري', familyEn: 'Al-Mutairi Family',
    sellerCity: 'الرياض', sellerCityEn: 'Riyadh',
    price: 220, originalPrice: null, rating: 4.9, reviews: 67,
    badge: 'حرفة تراثية', badgeEn: 'Heritage Craft', badgeColor: 'bg-amber-700',
    emoji: '🧶', images: ['🧶', '🎨', '✂️', '🪡', '🏡'],
    gradient: 'from-rose-100 to-pink-50',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'مسند سدو بدوي منسوج يدوياً بأنماط هندسية تراثية أصيلة بخيوط الصوف الطبيعي. كل قطعة فريدة ومميزة تعكس التراث البدوي النجدي وتُصنع بتقنية الأسرة التقليدية الموروثة.',
    descriptionEn: 'Handwoven Bedouin Sadu cushion with authentic geometric heritage patterns in natural wool threads. Each piece is unique and reflects Najdi Bedouin heritage, made using the family\'s inherited traditional technique.',
    weight: '40×40 سم', weightEn: '40×40 cm',
    preparationTime: 'تُنسج عند الطلب (7-14 يوم)', preparationTimeEn: 'Woven to order (7-14 days)',
    partnerSince: 'مارس 2021', partnerSinceEn: 'March 2021',
    stock: 8, certifications: ['يدوي 100%', 'صوف طبيعي'], certificationsEn: ['100% Handmade', 'Natural Wool'],
    orderCutoff: null, whatsapp: '+966501111034',
    sizes: [
      { id: 'sm', label: 'صغير 30×30 سم',   labelEn: 'Small 30×30 cm',   priceAdj: -80  },
      { id: 'md', label: 'متوسط 40×40 سم',  labelEn: 'Medium 40×40 cm',  priceAdj: 0    },
      { id: 'lg', label: 'كبير 60×60 سم',   labelEn: 'Large 60×60 cm',   priceAdj: 130  },
    ],
    colors: [
      { id: 'traditional', label: 'تقليدي (أحمر وأسود)', labelEn: 'Traditional (Red & Black)', hex: '#7B1515' },
      { id: 'desert',      label: 'صحراوي (بيج ورمادي)', labelEn: 'Desert (Beige & Gray)',     hex: '#C9A87A' },
      { id: 'indigo',      label: 'نيلي وأبيض',           labelEn: 'Indigo & White',            hex: '#1E3A5F' },
    ],
    isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتج غير المستخدم خلال 14 يوماً.',
    refundPolicyEn: 'Unused product can be returned within 14 days.',
    specifications: { 'المادة': 'صوف طبيعي 100%', 'الحجم': '40×40 سم', 'الصنع': 'يدوي بالكامل', 'الأنماط': 'هندسية بدوية تقليدية' },
    specificationsEn: { 'Material': '100% natural wool', 'Size': '40×40 cm', 'Making': 'Fully handmade', 'Patterns': 'Traditional Bedouin geometric' },
  },

  {
    id: 35, category: 'crafts',
    name: 'سلة خوص منسوجة يدوياً',
    nameEn: 'Handwoven Palm Leaf Basket',
    family: 'أسرة الحجازي', familyEn: 'Al-Hijazi Family',
    sellerCity: 'جدة', sellerCityEn: 'Jeddah',
    price: 90, originalPrice: null, rating: 4.7, reviews: 88,
    badge: null, badgeEn: null, badgeColor: 'bg-gray-400',
    emoji: '🧺', images: ['🧺', '🌴', '✂️', '🪡', '🎨'],
    gradient: 'from-amber-100 to-stone-50',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'سلة خوص حجازية منسوجة يدوياً من سعف النخيل الطبيعي. تُستخدم للتزيين أو لحمل الفواكه والتمور. كل سلة تُنسج بنمط مختلف يعكس تراث الحرف اليدوية الحجازية الأصيلة.',
    descriptionEn: 'Hejazi handwoven palm leaf basket made from natural palm fronds. Used for decoration or carrying fruits and dates. Each basket is woven in a unique pattern reflecting authentic Hejazi handicraft heritage.',
    weight: 'قطر 30 سم', weightEn: '30 cm diameter',
    preparationTime: 'تُنسج عند الطلب', preparationTimeEn: 'Woven to order',
    partnerSince: 'أكتوبر 2022', partnerSinceEn: 'October 2022',
    stock: 15, certifications: ['يدوي 100%', 'طبيعي'], certificationsEn: ['100% Handmade', 'Natural Materials'],
    orderCutoff: null, whatsapp: '+966501111035',
    sizes: [
      { id: 'sm', label: 'صغيرة (قطر 20 سم)', labelEn: 'Small (20 cm)',  priceAdj: -40 },
      { id: 'md', label: 'متوسطة (قطر 30 سم)', labelEn: 'Medium (30 cm)', priceAdj: 0  },
      { id: 'lg', label: 'كبيرة (قطر 45 سم)', labelEn: 'Large (45 cm)',  priceAdj: 55  },
    ],
    colors: [
      { id: 'natural',  label: 'طبيعي بيج',         labelEn: 'Natural Beige',       hex: '#D4B896' },
      { id: 'colorful', label: 'ملون تقليدي',         labelEn: 'Traditional Colorful', hex: '#C9A84C' },
    ],
    isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتج غير التالف خلال 14 يوماً.',
    refundPolicyEn: 'Undamaged product can be returned within 14 days.',
    specifications: { 'المادة': 'سعف نخيل طبيعي', 'القطر': '30 سم', 'الصنع': 'يدوي بالكامل', 'الاستخدام': 'تزيين، فواكه، تمور' },
    specificationsEn: { 'Material': 'Natural palm fronds', 'Diameter': '30 cm', 'Making': 'Fully handmade', 'Use': 'Decoration, fruits, dates' },
  },

  {
    id: 36, category: 'crafts',
    name: 'مبخرة فخارية مزخرفة',
    nameEn: 'Decorative Clay Incense Burner',
    family: 'أسرة الأنصاري', familyEn: 'Al-Ansari Family',
    sellerCity: 'المدينة المنورة', sellerCityEn: 'Medina',
    price: 75, originalPrice: null, rating: 4.8, reviews: 112,
    badge: null, badgeEn: null, badgeColor: 'bg-gray-400',
    emoji: '🪔', images: ['🪔', '🫙', '🎨', '✨', '🌿'],
    gradient: 'from-stone-200 to-amber-100',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'مبخرة فخارية مصنوعة يدوياً من الطين الطبيعي ومزخرفة بنقوش هندسية إسلامية بأصباغ طبيعية. تُستخدم للبخور والعود وتضيف لمسة تراثية رائعة لديكور المنزل.',
    descriptionEn: 'Handmade clay incense burner decorated with geometric Islamic patterns using natural dyes. Used for incense and Oud, adding a wonderful heritage touch to home decor.',
    weight: 'ارتفاع 15 سم', weightEn: '15 cm height',
    preparationTime: 'تُصنع عند الطلب', preparationTimeEn: 'Made to order',
    partnerSince: 'يونيو 2021', partnerSinceEn: 'June 2021',
    stock: 20, certifications: ['يدوي 100%', 'طيني طبيعي'], certificationsEn: ['100% Handmade', 'Natural Clay'],
    orderCutoff: null, whatsapp: '+966501111036',
    sizes: [
      { id: 'sm', label: 'صغيرة (10 سم)',  labelEn: 'Small (10 cm)',  priceAdj: -30 },
      { id: 'md', label: 'متوسطة (15 سم)', labelEn: 'Medium (15 cm)', priceAdj: 0   },
      { id: 'lg', label: 'كبيرة (20 سم)',  labelEn: 'Large (20 cm)',  priceAdj: 40  },
    ],
    colors: [
      { id: 'clay',   label: 'طيني طبيعي',    labelEn: 'Natural Clay',   hex: '#A0522D' },
      { id: 'blue',   label: 'أزرق إسلامي',   labelEn: 'Islamic Blue',   hex: '#1D4ED8' },
      { id: 'green',  label: 'أخضر زمردي',    labelEn: 'Emerald Green',  hex: '#065F46' },
    ],
    isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتج غير التالف خلال 14 يوماً.',
    refundPolicyEn: 'Undamaged product can be returned within 14 days.',
    specifications: { 'المادة': 'طين طبيعي مُحروق', 'الارتفاع': '15 سم', 'الصنع': 'يدوي بالكامل', 'الزخرفة': 'نقوش هندسية إسلامية' },
    specificationsEn: { 'Material': 'Fired natural clay', 'Height': '15 cm', 'Making': 'Fully handmade', 'Decoration': 'Islamic geometric patterns' },
  },

  // ══════════════════════════════════════════════════════════════════════════
  // DATES — Non-Perishable · Ships Nationwide
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 5, category: 'dates',
    name: 'حلوى التمر بالمكسرات الفاخرة',
    nameEn: 'Premium Date Candy with Luxury Nuts',
    family: 'أسرة الدوسري', familyEn: 'Al-Dosari Family',
    sellerCity: 'المدينة المنورة', sellerCityEn: 'Medina',
    price: 60, originalPrice: null, rating: 4.6, reviews: 156,
    badge: null, badgeEn: null, badgeColor: 'bg-gray-400',
    emoji: '🌴', images: ['🌴', '🥜', '🫙', '🍫', '🌰'],
    gradient: 'from-stone-200 to-amber-100',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'حلوى تمر فاخرة من أجود التمور، محشوة بالمكسرات المتنوعة كاللوز والجوز والكاجو. تُعدّ يدوياً بطريقة تقليدية متوارثة عبر الأجيال.',
    descriptionEn: 'Luxury date candy from the finest dates, stuffed with assorted nuts including almonds, walnuts, and cashews. Handcrafted in a traditional method passed down through generations.',
    weight: '400 جرام (~20 قطعة)', weightEn: '400g (~20 pieces)',
    preparationTime: 'تُجهّز عند الطلب', preparationTimeEn: 'Prepared to order',
    partnerSince: 'أغسطس 2022', partnerSinceEn: 'August 2022',
    stock: 28, certifications: ['طبيعي'], certificationsEn: ['Halal', 'Natural'],
    orderCutoff: null, whatsapp: '+966501111005',
    sizes: [
      { id: 'sm', label: '200 جرام (~10 قطع)',  labelEn: '200g (~10 pcs)',  priceAdj: -25 },
      { id: 'md', label: '400 جرام (~20 قطعة)', labelEn: '400g (~20 pcs)',  priceAdj: 0   },
      { id: 'lg', label: '800 جرام (~40 قطعة)', labelEn: '800g (~40 pcs)',  priceAdj: 50  },
    ],
    colors: [
      { id: 'gold',  label: 'علبة ذهبية',  labelEn: 'Gold Box',   hex: '#C9A84C' },
      { id: 'brown', label: 'علبة بني',    labelEn: 'Brown Box',  hex: '#7B3F00' },
      { id: 'green', label: 'علبة خضراء', labelEn: 'Green Box',  hex: '#1C5C2E' },
    ],
    isRefundable: true,
    refundPolicy: 'يمكن إرجاع علب الهدايا غير المفتوحة خلال 7 أيام.',
    refundPolicyEn: 'Unopened gift boxes can be returned within 7 days.',
    specifications: { 'المكونات': 'تمر عجوة، لوز، جوز، كاجو، هيل', 'الوزن': '400 جرام', 'الصلاحية': '3 أشهر', 'التغليف': 'علبة هدايا فاخرة' },
    specificationsEn: { 'Ingredients': 'Ajwa dates, almonds, walnuts, cashews, cardamom', 'Weight': '400g', 'Shelf Life': '3 months', 'Packaging': 'Luxury gift box' },
  },

  {
    id: 37, category: 'dates',
    name: 'تمر العجوة المدنية الفاخر',
    nameEn: 'Premium Medinese Ajwa Dates',
    family: 'أسرة الأنصاري', familyEn: 'Al-Ansari Family',
    sellerCity: 'المدينة المنورة', sellerCityEn: 'Medina',
    price: 85, originalPrice: null, rating: 5.0, reviews: 423,
    badge: 'مميز', badgeEn: 'Premium', badgeColor: 'bg-emerald-600',
    emoji: '🫒', images: ['🫒', '🌴', '🫙', '📦', '✨'],
    gradient: 'from-stone-300 to-amber-200',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'تمر العجوة المدني الأصيل من أعرق نخيل المدينة المنورة. نكهة حلوة عميقة وقوام ناعم لا مثيل له. يُذكر في السنة النبوية بفضائله الصحية المتعددة. هدية مثالية لكل المناسبات.',
    descriptionEn: 'Authentic Medinese Ajwa dates from the most prestigious palm trees of Medina. Deep sweet flavor and unmatched smooth texture. Mentioned in prophetic tradition for its multiple health benefits. A perfect gift for all occasions.',
    weight: '500 جرام', weightEn: '500g',
    preparationTime: 'تُجمع موسمياً وتُعبَّأ يدوياً', preparationTimeEn: 'Harvested seasonally and hand-packed',
    partnerSince: 'يناير 2020', partnerSinceEn: 'January 2020',
    stock: 30, certifications: ['طبيعي', 'مدني أصيل'], certificationsEn: ['Halal', 'Natural', 'Authentic Medinese'],
    orderCutoff: null, whatsapp: '+966501111037',
    sizes: [
      { id: 'sm', label: '250 جرام', labelEn: '250g', priceAdj: -38 },
      { id: 'md', label: '500 جرام', labelEn: '500g', priceAdj: 0   },
      { id: 'lg', label: '1 كيلو',   labelEn: '1kg',  priceAdj: 75  },
    ],
    colors: [
      { id: 'simple',  label: 'تغليف عادي',   labelEn: 'Simple Pack',  hex: '#78350F' },
      { id: 'gift',    label: 'علبة هدايا',   labelEn: 'Gift Box',     hex: '#C9A84C' },
    ],
    isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتج غير المفتوح خلال 14 يوماً.',
    refundPolicyEn: 'Unopened product can be returned within 14 days.',
    specifications: { 'النوع': 'عجوة مدنية أصيلة', 'الوزن': '500 جرام', 'الصلاحية': '12 شهراً', 'التخزين': 'مكان جاف بعيداً عن الشمس' },
    specificationsEn: { 'Type': 'Authentic Medinese Ajwa', 'Weight': '500g', 'Shelf Life': '12 months', 'Storage': 'Dry place away from sunlight' },
  },

  {
    id: 38, category: 'dates',
    name: 'تمر المدجول الممتاز',
    nameEn: 'Premium Medjool Dates',
    family: 'أسرة القرشي', familyEn: 'Al-Qurashi Family',
    sellerCity: 'مكة المكرمة', sellerCityEn: 'Mecca',
    price: 95, originalPrice: null, rating: 4.8, reviews: 189,
    badge: null, badgeEn: null, badgeColor: 'bg-gray-400',
    emoji: '🌰', images: ['🌰', '🌴', '🫙', '📦', '🍯'],
    gradient: 'from-amber-200 to-yellow-100',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'تمر المدجول الممتاز بحجمه الكبير ومذاقه الحلو المميز وقوامه الكريمي الطري. يُعبَّأ بعناية في علب مميزة. مثالي كهدية فاخرة أو للاستهلاك اليومي.',
    descriptionEn: 'Premium Medjool dates with their large size, distinctive sweet taste and creamy soft texture. Carefully packaged in special boxes. Perfect as a luxury gift or for daily consumption.',
    weight: '500 جرام', weightEn: '500g',
    preparationTime: 'تُجمع وتُعبَّأ يدوياً', preparationTimeEn: 'Harvested and hand-packed',
    partnerSince: 'يونيو 2021', partnerSinceEn: 'June 2021',
    stock: 25, certifications: ['طبيعي', 'ممتاز'], certificationsEn: ['Halal', 'Natural', 'Premium'],
    orderCutoff: null, whatsapp: '+966501111038',
    sizes: [
      { id: 'sm', label: '250 جرام', labelEn: '250g', priceAdj: -42 },
      { id: 'md', label: '500 جرام', labelEn: '500g', priceAdj: 0   },
      { id: 'lg', label: '1 كيلو',   labelEn: '1kg',  priceAdj: 82  },
    ],
    colors: [
      { id: 'simple', label: 'تغليف عادي', labelEn: 'Simple Pack', hex: '#78350F' },
      { id: 'luxury', label: 'علبة فاخرة', labelEn: 'Luxury Box',  hex: '#C9A84C' },
    ],
    isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتج غير المفتوح خلال 14 يوماً.',
    refundPolicyEn: 'Unopened product can be returned within 14 days.',
    specifications: { 'النوع': 'مدجول ممتاز', 'الوزن': '500 جرام', 'الصلاحية': '6 أشهر', 'التخزين': 'ثلاجة للحفاظ على الطراوة' },
    specificationsEn: { 'Type': 'Premium Medjool', 'Weight': '500g', 'Shelf Life': '6 months', 'Storage': 'Refrigerate to maintain freshness' },
  },

  {
    id: 39, category: 'dates',
    name: 'تمر الصفاوي من نخيل ينبع',
    nameEn: 'Safawi Dates from Yanbu Palms',
    family: 'أسرة الينبعاوي', familyEn: 'Al-Yanbuawi Family',
    sellerCity: 'ينبع', sellerCityEn: 'Yanbu',
    price: 55, originalPrice: null, rating: 4.5, reviews: 97,
    badge: null, badgeEn: null, badgeColor: 'bg-gray-400',
    emoji: '🌴', images: ['🌴', '🫙', '🌿', '📦', '✨'],
    gradient: 'from-stone-200 to-amber-100',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'تمر الصفاوي المميز بلونه الأسود الغامق ومذاقه الحلو مع لمسة من الإجماع. يُجمع من نخيل ينبع ويُعبَّأ بعناية. غني بالحديد ومضادات الأكسدة. مثالي للتناول اليومي والهدايا.',
    descriptionEn: 'Safawi dates distinguished by their dark black color and sweet taste with a touch of richness. Harvested from Yanbu palms and carefully packaged. Rich in iron and antioxidants. Perfect for daily consumption and gifts.',
    weight: '500 جرام', weightEn: '500g',
    preparationTime: 'تُجمع وتُعبَّأ موسمياً', preparationTimeEn: 'Harvested and packed seasonally',
    partnerSince: 'سبتمبر 2022', partnerSinceEn: 'September 2022',
    stock: 35, certifications: ['طبيعي'], certificationsEn: ['Halal', 'Natural'],
    orderCutoff: null, whatsapp: '+966501111039',
    sizes: [
      { id: 'sm', label: '250 جرام', labelEn: '250g', priceAdj: -25 },
      { id: 'md', label: '500 جرام', labelEn: '500g', priceAdj: 0   },
      { id: 'lg', label: '1 كيلو',   labelEn: '1kg',  priceAdj: 45  },
    ],
    colors: null, isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتج غير المفتوح خلال 14 يوماً.',
    refundPolicyEn: 'Unopened product can be returned within 14 days.',
    specifications: { 'النوع': 'صفاوي', 'الوزن': '500 جرام', 'الصلاحية': '12 شهراً', 'التخزين': 'مكان جاف أو ثلاجة' },
    specificationsEn: { 'Type': 'Safawi', 'Weight': '500g', 'Shelf Life': '12 months', 'Storage': 'Dry place or refrigerate' },
  },

  // ══════════════════════════════════════════════════════════════════════════
  // OTHER — Non-Perishable · Ships Nationwide
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 6, category: 'other',
    name: 'مربى التين البلدي المنزلية',
    nameEn: 'Homemade Wild Fig Jam',
    family: 'أسرة الشمري', familyEn: 'Al-Shamri Family',
    sellerCity: 'ينبع', sellerCityEn: 'Yanbu',
    price: 35, originalPrice: null, rating: 4.5, reviews: 78,
    badge: null, badgeEn: null, badgeColor: 'bg-gray-400',
    emoji: '🫐', images: ['🫐', '🍯', '🫙', '🌿', '🍞'],
    gradient: 'from-purple-200 to-violet-100',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'مربى تين بلدي منزلية مصنوعة من ثمار التين الطازجة. تُطهى ببطء مع السكر الطبيعي دون أي مواد حافظة أو مضافات صناعية.',
    descriptionEn: 'Homemade wild fig jam made from fresh figs. Slow-cooked with natural sugar without any preservatives or artificial additives.',
    weight: '350 جرام', weightEn: '350g',
    preparationTime: 'تُعدّ موسمياً', preparationTimeEn: 'Prepared seasonally',
    partnerSince: 'مايو 2023', partnerSinceEn: 'May 2023',
    stock: 35, certifications: ['طبيعي', 'خالٍ من المواد الحافظة'],
    certificationsEn: ['Halal', 'Natural', 'Preservative-free'],
    orderCutoff: null, whatsapp: '+966501111006',
    sizes: [
      { id: 'sm', label: '200 جرام', labelEn: '200g', priceAdj: -12 },
      { id: 'md', label: '350 جرام', labelEn: '350g', priceAdj: 0   },
      { id: 'lg', label: '700 جرام', labelEn: '700g', priceAdj: 28  },
    ],
    colors: [
      { id: 'fig',     label: 'تين بلدي', labelEn: 'Wild Fig',  hex: '#6D28D9' },
      { id: 'apricot', label: 'مشمش',     labelEn: 'Apricot',   hex: '#D97706' },
      { id: 'berry',   label: 'توت أحمر', labelEn: 'Red Berry', hex: '#BE185D' },
    ],
    isRefundable: true,
    refundPolicy: 'يمكن إرجاع البرطمانات غير المفتوحة خلال 14 يوماً.',
    refundPolicyEn: 'Unopened jars can be returned within 14 days.',
    specifications: { 'المكونات': 'تين بلدي طازج، سكر طبيعي، ليمون', 'الوزن': '350 جرام', 'الصلاحية': '6 أشهر بعد الفتح في الثلاجة' },
    specificationsEn: { 'Ingredients': 'Fresh wild figs, natural sugar, lemon', 'Weight': '350g', 'Shelf Life': '6 months after opening, refrigerated' },
  },

  {
    id: 40, category: 'other',
    name: 'زعتر مجفف وأعشاب حجازية',
    nameEn: 'Dried Thyme & Hejazi Herbs',
    family: 'أسرة البحري', familyEn: 'Al-Bahri Family',
    sellerCity: 'ينبع', sellerCityEn: 'Yanbu',
    price: 22, originalPrice: null, rating: 4.6, reviews: 145,
    badge: null, badgeEn: null, badgeColor: 'bg-gray-400',
    emoji: '🌿', images: ['🌿', '🫙', '☀️', '🌾', '🧄'],
    gradient: 'from-green-100 to-lime-50',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'زعتر حجازي طازج مجفف بالهواء الطلق والشمس الطبيعية. مزيج من الزعتر والمردقوش والأوريغانو. يُستخدم للخبز والسلطات وكمكون أساسي في فطائر الزعتر.',
    descriptionEn: 'Fresh Hejazi thyme dried in natural sunlight and open air. A blend of thyme, marjoram and oregano. Used for bread, salads and as a key ingredient in Zaatar pastries.',
    weight: '100 جرام', weightEn: '100g',
    preparationTime: 'يُجفَّف طبيعياً', preparationTimeEn: 'Naturally dried',
    partnerSince: 'مارس 2023', partnerSinceEn: 'March 2023',
    stock: 70, certifications: ['عضوي', 'طبيعي'], certificationsEn: ['Organic', 'Natural', 'Halal'],
    orderCutoff: null, whatsapp: '+966501111040',
    sizes: [
      { id: 'sm', label: '50 جرام',  labelEn: '50g',  priceAdj: -9 },
      { id: 'md', label: '100 جرام', labelEn: '100g', priceAdj: 0  },
      { id: 'lg', label: '250 جرام', labelEn: '250g', priceAdj: 20 },
    ],
    colors: null, isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتج المغلق خلال 14 يوماً.',
    refundPolicyEn: 'Sealed product can be returned within 14 days.',
    specifications: { 'المكونات': 'زعتر، مردقوش، أوريغانو', 'الوزن': '100 جرام', 'الصلاحية': '18 شهراً', 'التخزين': 'مكان جاف بعيداً عن الشمس' },
    specificationsEn: { 'Ingredients': 'Thyme, marjoram, oregano', 'Weight': '100g', 'Shelf Life': '18 months', 'Storage': 'Dry place away from sunlight' },
  },

  {
    id: 41, category: 'other',
    name: 'قهوة عربية مطحونة بالهيل',
    nameEn: 'Arabic Ground Coffee with Cardamom',
    family: 'أسرة الرشيد', familyEn: 'Al-Rasheed Family',
    sellerCity: 'الرياض', sellerCityEn: 'Riyadh',
    price: 40, originalPrice: null, rating: 4.9, reviews: 334,
    badge: 'الأكثر مبيعاً', badgeEn: 'Best Seller', badgeColor: 'bg-amber-500',
    emoji: '☕', images: ['☕', '🫙', '🌿', '✨', '🏺'],
    gradient: 'from-amber-200 to-yellow-100',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'قهوة عربية مطحونة طازجة من حبوب القهوة البن اليمني والإثيوبي المحمص فاتح، مخلوطة بالهيل الطازج المطحون والزعفران. تُطحن عند الطلب للحفاظ على أقصى درجات النكهة.',
    descriptionEn: 'Freshly ground Arabic coffee from lightly roasted Yemeni and Ethiopian beans, mixed with freshly ground cardamom and saffron. Ground to order to preserve maximum flavor.',
    weight: '250 جرام', weightEn: '250g',
    preparationTime: 'تُطحن عند الطلب', preparationTimeEn: 'Ground to order',
    partnerSince: 'أكتوبر 2020', partnerSinceEn: 'October 2020',
    stock: 60, certifications: ['طبيعي', 'طازج'], certificationsEn: ['Natural', 'Fresh Ground', 'Halal'],
    orderCutoff: null, whatsapp: '+966501111041',
    sizes: [
      { id: 'sm', label: '125 جرام', labelEn: '125g', priceAdj: -17 },
      { id: 'md', label: '250 جرام', labelEn: '250g', priceAdj: 0   },
      { id: 'lg', label: '500 جرام', labelEn: '500g', priceAdj: 35  },
    ],
    colors: [
      { id: 'cardamom', label: 'بالهيل',          labelEn: 'With Cardamom',          hex: '#4D7C0F' },
      { id: 'saffron',  label: 'بالهيل والزعفران', labelEn: 'With Cardamom & Saffron', hex: '#C9A84C' },
      { id: 'plain',    label: 'سادة',             labelEn: 'Plain',                  hex: '#78350F' },
    ],
    isRefundable: true,
    refundPolicy: 'يمكن إرجاع المنتج المغلق خلال 7 أيام من تاريخ التسليم.',
    refundPolicyEn: 'Sealed product can be returned within 7 days of delivery.',
    specifications: { 'المكونات': 'بن يمني/إثيوبي محمص، هيل طازج، زعفران', 'الوزن': '250 جرام', 'الصلاحية': '6 أشهر', 'درجة الطحن': 'ناعمة مناسبة للدلة' },
    specificationsEn: { 'Ingredients': 'Yemeni/Ethiopian roasted coffee, fresh cardamom, saffron', 'Weight': '250g', 'Shelf Life': '6 months', 'Grind': 'Fine, suitable for Dallah pot' },
  },

  {
    id: 42, category: 'other',
    name: 'دبس رمان وتمر منزلي',
    nameEn: 'Homemade Pomegranate & Date Molasses',
    family: 'أسرة الغامدي', familyEn: 'Al-Ghamdi Family',
    sellerCity: 'جدة', sellerCityEn: 'Jeddah',
    price: 32, originalPrice: null, rating: 4.5, reviews: 89,
    badge: null, badgeEn: null, badgeColor: 'bg-gray-400',
    emoji: '🍎', images: ['🍎', '🫙', '🌴', '🍯', '🌿'],
    gradient: 'from-red-100 to-rose-50',
    isPerishable: false, deliveryType: 'nationwide',
    description: 'دبس رمان طبيعي مركّز مصنوع من عصير الرمان الطازج، ودبس تمر طبيعي من أجود التمور. يُستخدمان في الطبخ والسلطات ودهن الخبز. بدون سكر مضاف أو مواد حافظة.',
    descriptionEn: 'Natural concentrated pomegranate molasses made from fresh pomegranate juice, and natural date molasses from premium dates. Used in cooking, salads and bread. No added sugar or preservatives.',
    weight: '400 مل (2 برطمان)', weightEn: '400ml (2 jars)',
    preparationTime: 'تُعصر وتُطهى منزلياً', preparationTimeEn: 'Home-pressed and cooked',
    partnerSince: 'ديسمبر 2022', partnerSinceEn: 'December 2022',
    stock: 45, certifications: ['طبيعي', 'بدون سكر مضاف'], certificationsEn: ['Natural', 'No Added Sugar', 'Vegan'],
    orderCutoff: null, whatsapp: '+966501111042',
    sizes: [
      { id: 'pom',  label: 'دبس رمان فقط',  labelEn: 'Pomegranate only', priceAdj: 0  },
      { id: 'date', label: 'دبس تمر فقط',   labelEn: 'Date only',        priceAdj: -3 },
      { id: 'both', label: 'كلاهما معاً',   labelEn: 'Both together',    priceAdj: 22 },
    ],
    colors: null, isRefundable: true,
    refundPolicy: 'يمكن إرجاع البرطمانات غير المفتوحة خلال 14 يوماً.',
    refundPolicyEn: 'Unopened jars can be returned within 14 days.',
    specifications: { 'المكونات': 'رمان طازج 100% أو تمر طبيعي 100%', 'الحجم': '200 مل لكل برطمان', 'الصلاحية': '12 شهراً مغلقاً', 'التخزين': 'مكان بارد بعد الفتح' },
    specificationsEn: { 'Ingredients': '100% fresh pomegranate or 100% natural dates', 'Size': '200ml per jar', 'Shelf Life': '12 months sealed', 'Storage': 'Cool place after opening' },
  },

];
